Update schema-41310to41400.sql
apache/cloudstack pull request #3999
Opened 2020-03-30 17:29 UTC by andrijapanicsb

Keeping the snapshot on Primary storage only, was originally implemented for KVM+Ceph specifically as it seems since it's seriously broken for KVM+NFS/local in 4.11+ (and not applicable/doesn't affects VMware at all, while it accidentally works for XS+NFS as they share the same "strategy")

Thus update the desc so that KVM users don't find themselves scratching their head.
We would want to fix/implement this in 4.15 (?) since when using qcow2 the snaps can be kept "attached" to it, the same way they are now attached/part of the rbd image (Ceph)

ping @GabrielBrascher @wido @weizhouapache 

cc @nathanejohnson (you guys implemented this, right?)

2020-03-30 20:32 UTC, DaanHoogland commented on engine/schema/src/main/resources/META-INF/db/schema-41310to41400.sql
> +UPDATE `cloud`.`configuration` SET `description`='Indicates whether to always backup primary storage snapshot to secondary storage. Applicable for KVM + Ceph only.' WHERE  `name`='snapshot.backup.to.
nice to update in the db, but it needs updating in code: https://github.com/apache/cloudstack/blob/master/server/src/main/java/com/cloud/storage/snapshot/SnapshotManager.java#L59

2020-03-30 20:33 UTC, DaanHoogland submitted a review, later dismissed
:-1:

2020-03-30 20:34 UTC, DaanHoogland requested changes
please see my drunken comment

2020-03-30 21:21 UTC, andrijapanicsb commented
I love you comments ❤️  don't worry 😉  
say, what makes you think it's needed? this global setting is already in the DB - so my idea is to edit the DB.
The config key you've shared (AFAIK!?) would create a setting that doesn't exist, right? but since it's already there from 4.11.3, I thought to just update it?

2020-03-30 21:29 UTC, andrijapanicsb commented
@blueorangutan package

2020-03-30 21:30 UTC, blueorangutan commented
@andrijapanicsb a Jenkins job has been kicked to build packages. I'll keep you posted as I make progress.

2020-03-30 21:38 UTC, weizhouapache approved these changes
code LGTM

2020-03-30 21:56 UTC, blueorangutan commented
Packaging result: ✔centos7 ✔debian. JID-1108

2020-03-30 22:35 UTC, nvazquez approved these changes

2020-03-31 11:19 UTC, andrijapanicsb commented
![image](https://user-images.githubusercontent.com/45762285/78019648-56428780-7350-11ea-8209-bea0a4047146.png)
This was on both clean install and when 4.13.1-snapshot was upgraded to master (this PR code) -so it looks good <--- Works without the config key update 

Will rebuild just for the sake of re-testing (and upgrade my envs)

2020-03-31 11:22 UTC, andrijapanicsb commented
@blueorangutan package

2020-03-31 11:22 UTC, blueorangutan commented
@andrijapanicsb a Jenkins job has been kicked to build packages. I'll keep you posted as I make progress.

2020-03-31 11:48 UTC, blueorangutan commented
Packaging result: ✔centos7 ✔debian. JID-1110

2020-03-31 12:46 UTC, andrijapanicsb commented
Doesn't count from my side - but this one is LGTM after manual testing

2020-03-31 12:52 UTC, andrijapanicsb commented
for the sake of fun, I don't find the tests needed for this change.

@blueorangutan test

2020-03-31 12:53 UTC, blueorangutan commented
@andrijapanicsb a Trillian-Jenkins test job (centos7 mgmt + kvm-centos7) has been kicked to run smoke tests

2020-04-01 20:51 UTC, DaanHoogland commented
this PR looks good, despite travis :(

2020-04-02 03:45 UTC, blueorangutan commented
<b>Trillian test result (tid-1341)</b>
Environment: kvm-centos7 (x2), Advanced Networking with Mgmt server 7
Total time taken: 138465 seconds
Marvin logs: https://github.com/blueorangutan/acs-prs/releases/download/trillian/pr3999-t1341-kvm-centos7.zip
Intermittent failure detected: /marvin/tests/smoke/test_accounts.py
Intermittent failure detected: /marvin/tests/smoke/test_affinity_groups_projects.py
Intermittent failure detected: /marvin/tests/smoke/test_async_job.py
Intermittent failure detected: /marvin/tests/smoke/test_deploy_virtio_scsi_vm.py
Intermittent failure detected: /marvin/tests/smoke/test_deploy_vm_iso.py
Intermittent failure detected: /marvin/tests/smoke/test_deploy_vms_with_varied_deploymentplanners.py
Intermittent failure detected: /marvin/tests/smoke/test_deploy_vm_with_userdata.py
Intermittent failure detected: /marvin/tests/smoke/test_diagnostics.py
Intermittent failure detected: /marvin/tests/smoke/test_domain_service_offerings.py
Intermittent failure detected: /marvin/tests/smoke/test_global_settings.py
Intermittent failure detected: /marvin/tests/smoke/test_internal_lb.py
Intermittent failure detected: /marvin/tests/smoke/test_iso.py
Intermittent failure detected: /marvin/tests/smoke/test_list_ids_parameter.py
Intermittent failure detected: /marvin/tests/smoke/test_loadbalance.py
Intermittent failure detected: /marvin/tests/smoke/test_metrics_api.py
Intermittent failure detected: /marvin/tests/smoke/test_multipleips_per_nic.py
Intermittent failure detected: /marvin/tests/smoke/test_nested_virtualization.py
Intermittent failure detected: /marvin/tests/smoke/test_network_acl.py
Intermittent failure detected: /marvin/tests/smoke/test_network.py
Intermittent failure detected: /marvin/tests/smoke/test_nic_adapter_type.py
Intermittent failure detected: /marvin/tests/smoke/test_password_server.py
Intermittent failure detected: /marvin/tests/smoke/test_portforwardingrules.py
Intermittent failure detected: /marvin/tests/smoke/test_privategw_acl.py
Intermittent failure detected: /marvin/tests/smoke/test_projects.py
Intermittent failure detected: /marvin/tests/smoke/test_reset_vm_on_reboot.py
Intermittent failure detected: /marvin/tests/smoke/test_resource_accounting.py
Intermittent failure detected: /marvin/tests/smoke/test_router_dhcphosts.py
Intermittent failure detected: /marvin/tests/smoke/test_router_dns.py
Intermittent failure detected: /marvin/tests/smoke/test_router_dnsservice.py
Intermittent failure detected: /marvin/tests/smoke/test_routers_iptables_default_policy.py
Intermittent failure detected: /marvin/tests/smoke/test_routers_network_ops.py
Intermittent failure detected: /marvin/tests/smoke/test_routers.py
Intermittent failure detected: /marvin/tests/smoke/test_service_offerings.py
Intermittent failure detected: /marvin/tests/smoke/test_snapshots.py
Intermittent failure detected: /marvin/tests/smoke/test_templates.py
Intermittent failure detected: /marvin/tests/smoke/test_usage.py
Intermittent failure detected: /marvin/tests/smoke/test_vm_life_cycle.py
Intermittent failure detected: /marvin/tests/smoke/test_vpc_redundant.py
Intermittent failure detected: /marvin/tests/smoke/test_vpc_router_nics.py
Intermittent failure detected: /marvin/tests/smoke/test_vpc_vpn.py
Intermittent failure detected: /marvin/tests/smoke/test_host_maintenance.py
Intermittent failure detected: /marvin/tests/smoke/test_hostha_kvm.py
Smoke tests completed. 35 look OK, 42 have error(s)
Only failed tests results shown below:


Test | Result | Time (s) | Test File
--- | --- | --- | ---
ContextSuite context=TestAccounts>:setup | `Error` | 0.00 | test_accounts.py
ContextSuite context=TestAddVmToSubDomain>:setup | `Error` | 0.00 | test_accounts.py
test_DeleteDomain | `Error` | 0.69 | test_accounts.py
test_forceDeleteDomain | `Error` | 0.69 | test_accounts.py
ContextSuite context=TestRemoveUserFromAccount>:setup | `Error` | 4.93 | test_accounts.py
ContextSuite context=TestDeployVmWithAffinityGroup>:setup | `Error` | 0.00 | test_affinity_groups_projects.py
test_UpdateConfigParamWithScope | `Error` | 0.07 | test_global_settings.py
ContextSuite context=TestAsyncJob>:setup | `Error` | 0.00 | test_async_job.py
ContextSuite context=TestDeployVirtioSCSIVM>:setup | `Error` | 0.00 | test_deploy_virtio_scsi_vm.py
ContextSuite context=TestDeployVMFromISO>:setup | `Error` | 0.00 | test_deploy_vm_iso.py
ContextSuite context=TestInternalLb>:setup | `Error` | 0.00 | test_internal_lb.py
ContextSuite context=TestDeployVmWithVariedPlanners>:setup | `Error` | 0.00 | test_deploy_vms_with_varied_deploymentplanners.py
ContextSuite context=TestDeployVmWithUserData>:setup | `Error` | 0.00 | test_deploy_vm_with_userdata.py
test_01_create_iso_with_checksum_sha1 | `Error` | 65.36 | test_iso.py
test_02_create_iso_with_checksum_sha256 | `Error` | 65.35 | test_iso.py
test_03_create_iso_with_checksum_md5 | `Error` | 65.33 | test_iso.py
test_04_create_iso_with_no_checksum | `Error` | 65.36 | test_iso.py
test_01_create_iso | `Failure` | 1511.25 | test_iso.py
ContextSuite context=TestISO>:setup | `Error` | 3023.66 | test_iso.py
ContextSuite context=TestRemoteDiagnostics>:setup | `Error` | 0.00 | test_diagnostics.py
ContextSuite context=TestLoadBalance>:setup | `Error` | 0.00 | test_loadbalance.py
ContextSuite context=TestDomainsServiceOfferings>:setup | `Error` | 1514.48 | test_domain_service_offerings.py
ContextSuite context=TestListIdsParams>:setup | `Error` | 0.00 | test_list_ids_parameter.py
test_list_clusters_metrics | `Error` | 1511.39 | test_metrics_api.py
test_list_vms_metrics | `Error` | 0.10 | test_metrics_api.py
test_nic_secondaryip_add_remove | `Error` | 1511.38 | test_multipleips_per_nic.py
ContextSuite context=TestNestedVirtualization>:setup | `Error` | 0.00 | test_nested_virtualization.py
ContextSuite context=TestNetworkACL>:setup | `Error` | 0.00 | test_network_acl.py
test_delete_account | `Error` | 1511.20 | test_network.py
test_delete_network_while_vm_on_it | `Error` | 0.05 | test_network.py
test_deploy_vm_l2network | `Error` | 0.05 | test_network.py
test_l2network_restart | `Error` | 1.12 | test_network.py
ContextSuite context=TestPortForwarding>:setup | `Error` | 3.33 | test_network.py
ContextSuite context=TestPublicIP>:setup | `Error` | 4.24 | test_network.py
test_reboot_router | `Error` | 0.05 | test_network.py
test_releaseIP | `Error` | 0.41 | test_network.py
ContextSuite context=TestRouterRules>:setup | `Error` | 0.46 | test_network.py
ContextSuite context=TestAdapterTypeForNic>:setup | `Error` | 0.00 | test_nic_adapter_type.py
ContextSuite context=TestIsolatedNetworksPasswdServer>:setup | `Error` | 0.00 | test_password_server.py
ContextSuite context=TestPortForwardingRules>:setup | `Error` | 0.00 | test_portforwardingrules.py
ContextSuite context=TestRouterServices>:setup | `Error` | 0.00 | test_routers.py
ContextSuite context=TestPrivateGwACL>:setup | `Error` | 0.00 | test_privategw_acl.py
ContextSuite context=TestProjectSuspendActivate>:setup | `Error` | 1518.03 | test_projects.py
ContextSuite context=TestRouterDnsService>:setup | `Error` | 0.00 | test_router_dnsservice.py
ContextSuite context=TestResetVmOnReboot>:setup | `Error` | 0.00 | test_reset_vm_on_reboot.py
ContextSuite context=TestRAMCPUResourceAccounting>:setup | `Error` | 0.00 | test_resource_accounting.py
ContextSuite context=TestRouterDHCPHosts>:setup | `Error` | 0.00 | test_router_dhcphosts.py
ContextSuite context=TestRouterDHCPOpts>:setup | `Error` | 0.00 | test_router_dhcphosts.py
ContextSuite context=TestRouterDns>:setup | `Error` | 0.00 | test_router_dns.py
ContextSuite context=TestRouterIpTablesPolicies>:setup | `Error` | 0.00 | test_routers_iptables_default_policy.py
ContextSuite context=TestVPCIpTablesPolicies>:setup | `Error` | 0.00 | test_routers_iptables_default_policy.py
ContextSuite context=TestIsolatedNetworks>:setup | `Error` | 0.00 | test_routers_network_ops.py
ContextSuite context=TestRedundantIsolateNetworks>:setup | `Error` | 0.00 | test_routers_network_ops.py
ContextSuite context= [...]

2020-04-03 18:40 UTC, blueorangutan commented
@andrijapanicsb a Jenkins job has been kicked to build packages. I'll keep you posted as I make progress.

2020-04-03 19:21 UTC, blueorangutan commented
Packaging result: ✔centos7 ✔debian. JID-1123

2020-04-03 19:37 UTC, andrijapanicsb commented
@blueorangutan test

2020-04-03 19:38 UTC, blueorangutan commented
@andrijapanicsb a Trillian-Jenkins test job (centos7 mgmt + kvm-centos7) has been kicked to run smoke tests

2020-04-04 07:49 UTC, blueorangutan commented
<b>Trillian test result (tid-1357)</b>
Environment: kvm-centos7 (x2), Advanced Networking with Mgmt server 7
Total time taken: 41869 seconds
Marvin logs: https://github.com/blueorangutan/acs-prs/releases/download/trillian/pr3999-t1357-kvm-centos7.zip
Intermittent failure detected: /marvin/tests/smoke/test_internal_lb.py
Smoke tests completed. 82 look OK, 1 have error(s)
Only failed tests results shown below:


Test | Result | Time (s) | Test File
--- | --- | --- | ---
test_04_rvpc_internallb_haproxy_stats_on_all_interfaces | `Error` | 186.87 | test_internal_lb.py

2020-04-04 12:07 UTC, andrijapanicsb commented
Looking good, 2 x LGTMs, manual testing regression testing OK (failed test nothing to do with the PR).

Merging.

2020-04-04 12:07 UTC, merged