[VMware] vSphere advanced capabilities and Full OVF properties support
apache/cloudstack pull request #4307
Opened 2020-09-07 18:03 UTC by nvazquez

## Description
Combined PR of #4248 and #4250

## Types of changes
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

## Screenshots (if appropriate):

## How Has This Been Tested?

2020-09-07 18:03 UTC, nvazquez commented
@blueorangutan package

2020-09-07 18:04 UTC, blueorangutan commented
@nvazquez a Jenkins job has been kicked to build packages. I'll keep you posted as I make progress.

2020-09-07 18:57 UTC, blueorangutan commented
Packaging result: ✔centos7 ✔centos8 ✔debian. JID-1911

2020-09-07 19:55 UTC, rhtyd commented
@blueorangutan test matrix

2020-09-07 19:56 UTC, blueorangutan commented
@rhtyd a Trillian-Jenkins matrix job (centos7 mgmt + xs71, centos7 mgmt + vmware67, centos7 mgmt + kvmcentos7) has been kicked to run smoke tests

2020-09-08 15:36 UTC, blueorangutan commented
<b>Trillian test result (tid-2697)</b>
Environment: kvm-centos7 (x2), Advanced Networking with Mgmt server 7
Total time taken: 68565 seconds
Marvin logs: https://github.com/blueorangutan/acs-prs/releases/download/trillian/pr4307-t2697-kvm-centos7.zip
Intermittent failure detected: /marvin/tests/smoke/test_kubernetes_clusters.py
Intermittent failure detected: /marvin/tests/smoke/test_kubernetes_supported_versions.py
Intermittent failure detected: /marvin/tests/smoke/test_privategw_acl.py
Intermittent failure detected: /marvin/tests/smoke/test_vpc_redundant.py
Intermittent failure detected: /marvin/tests/smoke/test_host_maintenance.py
Intermittent failure detected: /marvin/tests/smoke/test_hostha_kvm.py
Smoke tests completed. 81 look OK, 4 have error(s)
Only failed tests results shown below:


Test | Result | Time (s) | Test File
--- | --- | --- | ---
test_01_add_delete_kubernetes_supported_version | `Error` | 1807.37 | test_kubernetes_supported_versions.py
test_02_vpc_privategw_static_routes | `Failure` | 282.51 | test_privategw_acl.py
test_03_vpc_privategw_restart_vpc_cleanup | `Failure` | 266.32 | test_privategw_acl.py
test_04_rvpc_privategw_static_routes | `Failure` | 540.15 | test_privategw_acl.py
test_01_create_redundant_VPC_2tiers_4VMs_4IPs_4PF_ACL | `Failure` | 439.35 | test_vpc_redundant.py
test_03_create_redundant_VPC_1tier_2VMs_2IPs_2PF_ACL_reboot_routers | `Failure` | 587.17 | test_vpc_redundant.py
test_05_rvpc_multi_tiers | `Failure` | 517.08 | test_vpc_redundant.py
test_hostha_enable_ha_when_host_disabled | `Error` | 2.62 | test_hostha_kvm.py
test_hostha_enable_ha_when_host_in_maintenance | `Error` | 302.78 | test_hostha_kvm.py

2020-09-08 17:57 UTC, blueorangutan commented
<b>Trillian test result (tid-2698)</b>
Environment: vmware-67u3 (x2), Advanced Networking with Mgmt server 7
Total time taken: 75260 seconds
Marvin logs: https://github.com/blueorangutan/acs-prs/releases/download/trillian/pr4307-t2698-vmware-67u3.zip
Intermittent failure detected: /marvin/tests/smoke/test_iso.py
Intermittent failure detected: /marvin/tests/smoke/test_kubernetes_supported_versions.py
Intermittent failure detected: /marvin/tests/smoke/test_snapshots.py
Intermittent failure detected: /marvin/tests/smoke/test_ssvm.py
Smoke tests completed. 81 look OK, 4 have error(s)
Only failed tests results shown below:


Test | Result | Time (s) | Test File
--- | --- | --- | ---
test_03_create_iso_with_checksum_md5 | `Error` | 72.52 | test_iso.py
test_03_create_iso_with_checksum_md5 | `Error` | 73.56 | test_iso.py
test_04_create_iso_with_no_checksum | `Error` | 73.64 | test_iso.py
test_01_add_delete_kubernetes_supported_version | `Error` | 1813.90 | test_kubernetes_supported_versions.py
test_02_list_snapshots_with_removed_data_store | `Error` | 179.25 | test_snapshots.py
test_07_reboot_ssvm | `Failure` | 57.99 | test_ssvm.py

2020-09-09 04:58 UTC, harikrishna-patnala commented
@blueorangutan package

2020-09-09 04:59 UTC, blueorangutan commented
@harikrishna-patnala a Jenkins job has been kicked to build packages. I'll keep you posted as I make progress.

2020-09-09 05:37 UTC, blueorangutan commented
Packaging result: ✔centos7 ✔centos8 ✔debian. JID-1924

2020-09-09 13:10 UTC, blueorangutan commented
<b>Trillian test result (tid-2699)</b>
Environment: xenserver-71 (x2), Advanced Networking with Mgmt server 7
Total time taken: 101618 seconds
Marvin logs: https://github.com/blueorangutan/acs-prs/releases/download/trillian/pr4307-t2699-xenserver-71.zip
Intermittent failure detected: /marvin/tests/smoke/test_accounts.py
Intermittent failure detected: /marvin/tests/smoke/test_async_job.py
Intermittent failure detected: /marvin/tests/smoke/test_certauthority_root.py
Intermittent failure detected: /marvin/tests/smoke/test_deploy_vm_root_resize.py
Intermittent failure detected: /marvin/tests/smoke/test_domain_vpc_offerings.py
Intermittent failure detected: /marvin/tests/smoke/test_internal_lb.py
Intermittent failure detected: /marvin/tests/smoke/test_kubernetes_supported_versions.py
Intermittent failure detected: /marvin/tests/smoke/test_list_ids_parameter.py
Intermittent failure detected: /marvin/tests/smoke/test_network_acl.py
Intermittent failure detected: /marvin/tests/smoke/test_password_server.py
Intermittent failure detected: /marvin/tests/smoke/test_scale_vm.py
Smoke tests completed. 79 look OK, 6 have error(s)
Only failed tests results shown below:


Test | Result | Time (s) | Test File
--- | --- | --- | ---
ContextSuite context=TestAddVmToSubDomain>:setup | `Error` | 1849.30 | test_accounts.py
ContextSuite context=TestTemplateHierarchy>:setup | `Error` | 1529.07 | test_accounts.py
test_02_internallb_roundrobin_1RVPC_3VM_HTTP_port80 | `Error` | 0.10 | test_internal_lb.py
test_03_vpc_internallb_haproxy_stats_on_all_interfaces | `Failure` | 910.84 | test_internal_lb.py
test_04_rvpc_internallb_haproxy_stats_on_all_interfaces | `Failure` | 1027.43 | test_internal_lb.py
test_03_create_vpc_domain_vpc_offering | `Error` | 917.86 | test_domain_vpc_offerings.py
test_01_add_delete_kubernetes_supported_version | `Error` | 1807.56 | test_kubernetes_supported_versions.py
test_network_acl | `Error` | 912.02 | test_network_acl.py
test_01_scale_vm | `Failure` | 93.40 | test_scale_vm.py

2020-09-09 23:00 UTC, rhtyd commented
@blueorangutan test centos7 vmware-67u3

2020-09-09 23:01 UTC, blueorangutan commented
@rhtyd a Trillian-Jenkins test job (centos7 mgmt + vmware-67u3) has been kicked to run smoke tests

2020-09-10 10:57 UTC, harikrishna-patnala commented
@blueorangutan package

2020-09-10 10:58 UTC, blueorangutan commented
@harikrishna-patnala a Jenkins job has been kicked to build packages. I'll keep you posted as I make progress.

2020-09-10 11:33 UTC, blueorangutan commented
Packaging result: ✔centos7 ✔centos8 ✔debian. JID-1952

2020-09-10 17:02 UTC, blueorangutan commented
<b>Trillian test result (tid-2710)</b>
Environment: vmware-67u3 (x2), Advanced Networking with Mgmt server 7
Total time taken: 62629 seconds
Marvin logs: https://github.com/blueorangutan/acs-prs/releases/download/trillian/pr4307-t2710-vmware-67u3.zip
Intermittent failure detected: /marvin/tests/smoke/test_deploy_vm_root_resize.py
Intermittent failure detected: /marvin/tests/smoke/test_kubernetes_supported_versions.py
Intermittent failure detected: /marvin/tests/smoke/test_pvlan.py
Intermittent failure detected: /marvin/tests/smoke/test_scale_vm.py
Intermittent failure detected: /marvin/tests/smoke/test_snapshots.py
Intermittent failure detected: /marvin/tests/smoke/test_vm_deployment_planner.py
Intermittent failure detected: /marvin/tests/smoke/test_vpc_vpn.py
Smoke tests completed. 77 look OK, 6 have error(s)
Only failed tests results shown below:


Test | Result | Time (s) | Test File
--- | --- | --- | ---
test_00_deploy_vm_root_resize | `Failure` | 587.23 | test_deploy_vm_root_resize.py
test_01_add_delete_kubernetes_supported_version | `Error` | 1808.22 | test_kubernetes_supported_versions.py
test_create_pvlan_network | `Error` | 0.03 | test_pvlan.py
test_02_list_snapshots_with_removed_data_store | `Error` | 182.79 | test_snapshots.py
test_02_deploy_vm_on_specific_cluster | `Error` | 4.47 | test_vm_deployment_planner.py
test_03_deploy_vm_on_specific_pod | `Error` | 7.06 | test_vm_deployment_planner.py
ContextSuite context=TestRVPCSite2SiteVpn>:teardown | `Error` | 604.00 | test_vpc_vpn.py
ContextSuite context=TestVPCSite2SiteVPNMultipleOptions>:setup | `Error` | 604.03 | test_vpc_vpn.py
ContextSuite context=TestVpcRemoteAccessVpn>:setup | `Error` | 604.08 | test_vpc_vpn.py
ContextSuite context=TestVpcSite2SiteVpn>:setup | `Error` | 604.10 | test_vpc_vpn.py

2020-09-11 08:06 UTC, harikrishna-patnala commented
@blueorangutan package

2020-09-11 08:07 UTC, blueorangutan commented
@harikrishna-patnala a Jenkins job has been kicked to build packages. I'll keep you posted as I make progress.

2020-09-11 08:30 UTC, blueorangutan commented
Packaging result: ✖centos7 ✖centos8 ✖debian. JID-1956

2020-09-11 08:34 UTC, harikrishna-patnala commented
@blueorangutan package

2020-09-11 08:34 UTC, blueorangutan commented
@harikrishna-patnala a Jenkins job has been kicked to build packages. I'll keep you posted as I make progress.

2020-09-11 09:10 UTC, blueorangutan commented
Packaging result: ✖centos7 ✖centos8 ✖debian. JID-1958

2020-09-13 10:50 UTC, rhtyd commented
@blueorangutan package

2020-09-13 10:51 UTC, blueorangutan commented
@rhtyd a Jenkins job has been kicked to build packages. I'll keep you posted as I make progress.

2020-09-13 11:37 UTC, blueorangutan commented
Packaging result: ✖centos7 ✖centos8 ✖debian. JID-1986

2020-09-13 18:21 UTC, rhtyd commented
@blueorangutan package

2020-09-13 18:22 UTC, blueorangutan commented
@rhtyd a Jenkins job has been kicked to build packages. I'll keep you posted as I make progress.

2020-09-13 19:08 UTC, blueorangutan commented
Packaging result: ✖centos7 ✖centos8 ✖debian. JID-1988

2020-09-13 21:20 UTC, rhtyd commented
@blueorangutan package

2020-09-13 21:21 UTC, blueorangutan commented
@rhtyd a Jenkins job has been kicked to build packages. I'll keep you posted as I make progress.

2020-09-13 21:54 UTC, blueorangutan commented
Packaging result: ✔centos7 ✔centos8 ✔debian. JID-1989

2020-09-13 21:54 UTC, rhtyd commented
@blueorangutan test matrix

2020-09-13 21:56 UTC, blueorangutan commented
@rhtyd a Trillian-Jenkins matrix job (centos7 mgmt + xs71, centos7 mgmt + vmware67, centos7 mgmt + kvmcentos7) has been kicked to run smoke tests

2020-09-14 13:47 UTC, nvazquez commented
@blueorangutan package

2020-09-14 13:48 UTC, blueorangutan commented
@nvazquez a Jenkins job has been kicked to build packages. I'll keep you posted as I make progress.

2020-09-14 14:21 UTC, blueorangutan commented
Packaging result: ✔centos7 ✔centos8 ✔debian. JID-1997

2020-09-14 15:45 UTC, nvazquez commented
@blueorangutan package

2020-09-14 15:46 UTC, blueorangutan commented
@nvazquez a Jenkins job has been kicked to build packages. I'll keep you posted as I make progress.

2020-09-14 16:19 UTC, blueorangutan commented
Packaging result: ✔centos7 ✖centos8 ✔debian. JID-1998

2020-09-14 17:13 UTC, nvazquez commented
@blueorangutan package

2020-09-14 17:14 UTC, blueorangutan commented
@nvazquez a Jenkins job has been kicked to build packages. I'll keep you posted as I make progress.

2020-09-14 17:48 UTC, blueorangutan commented
Packaging result: ✔centos7 ✔centos8 ✔debian. JID-1999

2020-09-14 17:57 UTC, nvazquez commented
@blueorangutan package

2020-09-14 17:58 UTC, blueorangutan commented
@nvazquez a Jenkins job has been kicked to build packages. I'll keep you posted as I make progress.

2020-09-14 18:31 UTC, blueorangutan commented
Packaging result: ✔centos7 ✔centos8 ✔debian. JID-2000

2020-09-14 18:36 UTC, nvazquez commented
@blueorangutan package

2020-09-14 18:38 UTC, blueorangutan commented
@nvazquez a Jenkins job has been kicked to build packages. I'll keep you posted as I make progress.

2020-09-14 19:12 UTC, blueorangutan commented
Packaging result: ✔centos7 ✔centos8 ✔debian. JID-2001

2020-09-15 06:27 UTC, borisstoyanov commented
@blueorangutan test matrix

2020-09-15 06:28 UTC, blueorangutan commented
@borisstoyanov a Trillian-Jenkins matrix job (centos7 mgmt + xs71, centos7 mgmt + vmware67, centos7 mgmt + kvmcentos7) has been kicked to run smoke tests

2020-09-16 00:20 UTC, blueorangutan commented
<b>Trillian test result (tid-2738)</b>
Environment: xenserver-71 (x2), Advanced Networking with Mgmt server 7
Total time taken: 60199 seconds
Marvin logs: https://github.com/blueorangutan/acs-prs/releases/download/trillian/pr4307-t2738-xenserver-71.zip
Intermittent failure detected: /marvin/tests/smoke/test_accounts.py
Intermittent failure detected: /marvin/tests/smoke/test_internal_lb.py
Intermittent failure detected: /marvin/tests/smoke/test_kubernetes_supported_versions.py
Intermittent failure detected: /marvin/tests/smoke/test_scale_vm.py
Intermittent failure detected: /marvin/tests/smoke/test_ssvm.py
Intermittent failure detected: /marvin/tests/smoke/test_templates.py
Smoke tests completed. 70 look OK, 2 have error(s)
Only failed tests results shown below:


Test | Result | Time (s) | Test File
--- | --- | --- | ---
test_01_add_delete_kubernetes_supported_version | `Error` | 1810.22 | test_kubernetes_supported_versions.py
test_01_scale_vm | `Failure` | 15.89 | test_scale_vm.py

2020-09-16 02:58 UTC, blueorangutan commented
<b>Trillian test result (tid-2746)</b>
Environment: vmware-67u3 (x2), Advanced Networking with Mgmt server 7
Total time taken: 58775 seconds
Marvin logs: https://github.com/blueorangutan/acs-prs/releases/download/trillian/pr4307-t2746-vmware-67u3.zip
Intermittent failure detected: /marvin/tests/smoke/test_deploy_vm_root_resize.py
Intermittent failure detected: /marvin/tests/smoke/test_kubernetes_supported_versions.py
Intermittent failure detected: /marvin/tests/smoke/test_snapshots.py
Intermittent failure detected: /marvin/tests/smoke/test_vpc_vpn.py
Smoke tests completed. 80 look OK, 2 have error(s)
Only failed tests results shown below:


Test | Result | Time (s) | Test File
--- | --- | --- | ---
test_01_add_delete_kubernetes_supported_version | `Error` | 1817.83 | test_kubernetes_supported_versions.py
test_02_list_snapshots_with_removed_data_store | `Error` | 24.04 | test_snapshots.py

2020-09-16 03:32 UTC, blueorangutan commented
<b>Trillian test result (tid-2739)</b>
Environment: kvm-centos7 (x2), Advanced Networking with Mgmt server 7
Total time taken: 73046 seconds
Marvin logs: https://github.com/blueorangutan/acs-prs/releases/download/trillian/pr4307-t2739-kvm-centos7.zip
Intermittent failure detected: /marvin/tests/smoke/test_diagnostics.py
Intermittent failure detected: /marvin/tests/smoke/test_internal_lb.py
Intermittent failure detected: /marvin/tests/smoke/test_iso.py
Intermittent failure detected: /marvin/tests/smoke/test_kubernetes_supported_versions.py
Intermittent failure detected: /marvin/tests/smoke/test_outofbandmanagement.py
Intermittent failure detected: /marvin/tests/smoke/test_privategw_acl.py
Intermittent failure detected: /marvin/tests/smoke/test_router_dhcphosts.py
Intermittent failure detected: /marvin/tests/smoke/test_templates.py
Intermittent failure detected: /marvin/tests/smoke/test_host_maintenance.py
Intermittent failure detected: /marvin/tests/smoke/test_hostha_kvm.py
Smoke tests completed. 78 look OK, 7 have error(s)
Only failed tests results shown below:


Test | Result | Time (s) | Test File
--- | --- | --- | ---
test_03_vpc_internallb_haproxy_stats_on_all_interfaces | `Error` | 422.31 | test_internal_lb.py
test_04_extract_Iso | `Failure` | 128.09 | test_iso.py
test_01_add_delete_kubernetes_supported_version | `Error` | 1807.99 | test_kubernetes_supported_versions.py
test_02_vpc_privategw_static_routes | `Failure` | 534.25 | test_privategw_acl.py
test_03_vpc_privategw_restart_vpc_cleanup | `Failure` | 658.05 | test_privategw_acl.py
test_router_dhcphosts | `Failure` | 177.32 | test_router_dhcphosts.py
ContextSuite context=TestRouterDHCPHosts>:teardown | `Error` | 201.16 | test_router_dhcphosts.py
ContextSuite context=TestTemplates>:setup | `Error` | 1333.20 | test_templates.py
test_hostha_enable_ha_when_host_disabled | `Error` | 1.86 | test_hostha_kvm.py
test_hostha_enable_ha_when_host_in_maintenance | `Error` | 301.05 | test_hostha_kvm.py

2020-09-16 07:07 UTC, harikrishna-patnala commented
@blueorangutan package

2020-09-16 07:08 UTC, blueorangutan commented
@harikrishna-patnala a Jenkins job has been kicked to build packages. I'll keep you posted as I make progress.

2020-09-16 07:41 UTC, blueorangutan commented
Packaging result: ✔centos7 ✔centos8 ✔debian. JID-2017

2020-09-16 13:36 UTC, nvazquez commented
@blueorangutan package

2020-09-16 13:37 UTC, blueorangutan commented
@nvazquez a Jenkins job has been kicked to build packages. I'll keep you posted as I make progress.

2020-09-16 14:09 UTC, blueorangutan commented
Packaging result: ✔centos7 ✔centos8 ✔debian. JID-2018

2020-09-17 04:48 UTC, rhtyd commented
@harikrishna-patnala can you merge latest master and fix conflicts, then run pkging and smoketests?

2020-09-17 06:26 UTC, harikrishna-patnala commented
@blueorangutan package

2020-09-17 06:27 UTC, blueorangutan commented
@harikrishna-patnala a Jenkins job has been kicked to build packages. I'll keep you posted as I make progress.

2020-09-17 06:31 UTC, blueorangutan commented
Packaging result: ✖centos7 ✖centos8 ✖debian. JID-2024

2020-09-17 09:01 UTC, harikrishna-patnala commented
@blueorangutan package

2020-09-17 09:02 UTC, blueorangutan commented
@harikrishna-patnala a Jenkins job has been kicked to build packages. I'll keep you posted as I make progress.

2020-09-17 09:38 UTC, blueorangutan commented
Packaging result: ✔centos7 ✔centos8 ✔debian. JID-2027

2020-09-17 19:08 UTC, nvazquez commented
@blueorangutan package

2020-09-17 19:09 UTC, blueorangutan commented
@nvazquez a Jenkins job has been kicked to build packages. I'll keep you posted as I make progress.

2020-09-17 19:42 UTC, blueorangutan commented
Packaging result: ✔centos7 ✔centos8 ✔debian. JID-2029

2020-09-18 02:57 UTC, rhtyd commented
@blueorangutan test matrix

2020-09-18 02:59 UTC, blueorangutan commented
@rhtyd a Trillian-Jenkins matrix job (centos7 mgmt + xs71, centos7 mgmt + vmware67, centos7 mgmt + kvmcentos7) has been kicked to run smoke tests

2020-09-19 00:52 UTC, blueorangutan commented
<b>Trillian test result (tid-2778)</b>
Environment: xenserver-71 (x2), Advanced Networking with Mgmt server 7
Total time taken: 75593 seconds
Marvin logs: https://github.com/blueorangutan/acs-prs/releases/download/trillian/pr4307-t2778-xenserver-71.zip
Intermittent failure detected: /marvin/tests/smoke/test_accounts.py
Intermittent failure detected: /marvin/tests/smoke/test_kubernetes_clusters.py
Intermittent failure detected: /marvin/tests/smoke/test_kubernetes_supported_versions.py
Intermittent failure detected: /marvin/tests/smoke/test_list_ids_parameter.py
Intermittent failure detected: /marvin/tests/smoke/test_routers_network_ops.py
Intermittent failure detected: /marvin/tests/smoke/test_scale_vm.py
Intermittent failure detected: /marvin/tests/smoke/test_ssvm.py
Intermittent failure detected: /marvin/tests/smoke/test_vm_snapshots.py
Smoke tests completed. 83 look OK, 2 have error(s)
Only failed tests results shown below:


Test | Result | Time (s) | Test File
--- | --- | --- | ---
test_01_add_delete_kubernetes_supported_version | `Error` | 1807.62 | test_kubernetes_supported_versions.py
test_01_scale_vm | `Failure` | 34.92 | test_scale_vm.py

2020-09-20 02:24 UTC, nvazquez commented
@blueorangutan package

2020-09-20 02:25 UTC, blueorangutan commented
@nvazquez a Jenkins job has been kicked to build packages. I'll keep you posted as I make progress.

2020-09-20 02:55 UTC, blueorangutan commented
Packaging result: ✔centos7 ✔centos8 ✔debian. JID-2049

2020-09-20 03:15 UTC, nvazquez commented
@blueorangutan test

2020-09-20 03:16 UTC, blueorangutan commented
@nvazquez a Trillian-Jenkins test job (centos7 mgmt + kvm-centos7) has been kicked to run smoke tests

2020-09-20 17:05 UTC, rhtyd commented
@blueorangutan test matrix

2020-09-20 17:06 UTC, blueorangutan commented
@rhtyd a Trillian-Jenkins matrix job (centos7 mgmt + xs71, centos7 mgmt + vmware67, centos7 mgmt + kvmcentos7) has been kicked to run smoke tests

2020-09-21 03:15 UTC, nvazquez commented
@blueorangutan package

2020-09-21 03:17 UTC, blueorangutan commented
@nvazquez a Jenkins job has been kicked to build packages. I'll keep you posted as I make progress.

2020-09-21 03:47 UTC, blueorangutan commented
Packaging result: ✔centos7 ✔centos8 ✔debian. JID-2052

2020-09-21 06:41 UTC, blueorangutan commented
<b>Trillian test result (tid-2797)</b>
Environment: vmware-67u3 (x2), Advanced Networking with Mgmt server 7
Total time taken: 45833 seconds
Marvin logs: https://github.com/blueorangutan/acs-prs/releases/download/trillian/pr4307-t2797-vmware-67u3.zip
Intermittent failure detected: /marvin/tests/smoke/test_vpc_redundant.py
Smoke tests completed. 80 look OK, 1 have error(s)
Only failed tests results shown below:


Test | Result | Time (s) | Test File
--- | --- | --- | ---
test_01_create_redundant_VPC_2tiers_4VMs_4IPs_4PF_ACL | `Failure` | 497.47 | test_vpc_redundant.py
test_04_rvpc_network_garbage_collector_nics | `Error` | 3810.98 | test_vpc_redundant.py
test_04_rvpc_network_garbage_collector_nics | `Error` | 3811.01 | test_vpc_redundant.py
test_05_rvpc_multi_tiers | `Error` | 0.01 | test_vpc_redundant.py
ContextSuite context=TestVPCRedundancy>:teardown | `Error` | 0.01 | test_vpc_redundant.py

2020-09-22 04:04 UTC, nvazquez commented
@blueorangutan package

2020-09-22 04:05 UTC, blueorangutan commented
@nvazquez a Jenkins job has been kicked to build packages. I'll keep you posted as I make progress.

2020-09-22 04:14 UTC, rhtyd commented
@nvazquez @harikrishna-patnala can you resolve the schema conflict?

2020-09-22 05:05 UTC, blueorangutan commented
Packaging result: ✖centos7 ✔centos8 ✔debian. JID-2058

2020-09-22 07:10 UTC, harikrishna-patnala commented
@blueorangutan package

2020-09-22 07:11 UTC, blueorangutan commented
@harikrishna-patnala a Jenkins job has been kicked to build packages. I'll keep you posted as I make progress.

2020-09-22 07:44 UTC, blueorangutan commented
Packaging result: ✔centos7 ✔centos8 ✔debian. JID-2061

2020-09-23 00:16 UTC, nvazquez commented
@blueorangutan package

2020-09-23 00:17 UTC, blueorangutan commented
@nvazquez a Jenkins job has been kicked to build packages. I'll keep you posted as I make progress.

2020-09-23 00:50 UTC, blueorangutan commented
Packaging result: ✔centos7 ✔centos8 ✔debian. JID-2068

2020-09-23 05:29 UTC, rhtyd commented
@blueorangutan test centos7 vmware-67u3

2020-09-23 05:30 UTC, blueorangutan commented
@rhtyd a Trillian-Jenkins test job (centos7 mgmt + vmware-67u3) has been kicked to run smoke tests

2020-09-23 22:43 UTC, blueorangutan commented
<b>Trillian test result (tid-2839)</b>
Environment: vmware-67u3 (x2), Advanced Networking with Mgmt server 7
Total time taken: 59874 seconds
Marvin logs: https://github.com/blueorangutan/acs-prs/releases/download/trillian/pr4307-t2839-vmware-67u3.zip
Intermittent failure detected: /marvin/tests/smoke/test_deploy_vm_root_resize.py
Intermittent failure detected: /marvin/tests/smoke/test_kubernetes_clusters.py
Intermittent failure detected: /marvin/tests/smoke/test_kubernetes_supported_versions.py
Intermittent failure detected: /marvin/tests/smoke/test_vpc_redundant.py
Smoke tests completed. 85 look OK, 0 have error(s)
Only failed tests results shown below:


Test | Result | Time (s) | Test File
--- | --- | --- | ---

2020-09-24 00:01 UTC, harikrishna-patnala commented
@blueorangutan package

2020-09-24 00:02 UTC, blueorangutan commented
@harikrishna-patnala a Jenkins job has been kicked to build packages. I'll keep you posted as I make progress.

2020-09-24 00:34 UTC, blueorangutan commented
Packaging result: ✔centos7 ✔centos8 ✔debian. JID-2075

2020-09-24 05:31 UTC, rhtyd commented
@blueorangutan package

2020-09-24 05:32 UTC, blueorangutan commented
@rhtyd a Jenkins job has been kicked to build packages. I'll keep you posted as I make progress.

2020-09-24 06:20 UTC, blueorangutan commented
Packaging result: ✔centos7 ✔centos8 ✔debian. JID-2076

2020-09-24 10:38 UTC, harikrishna-patnala commented
@blueorangutan package

2020-09-24 10:38 UTC, blueorangutan commented
@harikrishna-patnala a Jenkins job has been kicked to build packages. I'll keep you posted as I make progress.

2020-09-24 11:12 UTC, blueorangutan commented
Packaging result: ✔centos7 ✔centos8 ✔debian. JID-2083

2020-09-25 03:31 UTC, rhtyd commented
@blueorangutan test matrix

2020-09-25 03:32 UTC, blueorangutan commented
@rhtyd a Trillian-Jenkins matrix job (centos7 mgmt + xs71, centos7 mgmt + vmware67, centos7 mgmt + kvmcentos7) has been kicked to run smoke tests

2020-09-25 04:44 UTC, nvazquez commented
@blueorangutan package

2020-09-25 04:45 UTC, blueorangutan commented
@nvazquez a Jenkins job has been kicked to build packages. I'll keep you posted as I make progress.

2020-09-25 05:20 UTC, blueorangutan commented
Packaging result: ✔centos7 ✔centos8 ✔debian. JID-2084

2020-09-25 06:39 UTC, nvazquez commented
@blueorangutan package

2020-09-25 06:40 UTC, blueorangutan commented
@nvazquez a Jenkins job has been kicked to build packages. I'll keep you posted as I make progress.

2020-09-25 06:43 UTC, nvazquez commented
@blueorangutan package

2020-09-25 06:44 UTC, blueorangutan commented
@nvazquez a Jenkins job has been kicked to build packages. I'll keep you posted as I make progress.

2020-09-25 07:33 UTC, blueorangutan commented
Packaging result: ✔centos7 ✔centos8 ✔debian. JID-2086

2020-09-25 10:02 UTC, borisstoyanov commented
@blueorangutan test centos7 vmware-67u3

2020-09-25 10:04 UTC, blueorangutan commented
@borisstoyanov a Trillian-Jenkins test job (centos7 mgmt + vmware-67u3) has been kicked to run smoke tests

2020-09-25 10:04 UTC, borisstoyanov commented
@blueorangutan test centos7 vmware-65u2

2020-09-25 10:05 UTC, blueorangutan commented
@borisstoyanov a Trillian-Jenkins test job (centos7 mgmt + vmware-65u2) has been kicked to run smoke tests

2020-09-25 12:55 UTC, rhtyd commented
Requesting review cc @sureshanaparti @DaanHoogland, thnx

2020-09-28 03:47 UTC, harikrishna-patnala commented
@blueorangutan package

2020-09-28 03:48 UTC, blueorangutan commented
@harikrishna-patnala a Jenkins job has been kicked to build packages. I'll keep you posted as I make progress.

2020-09-28 04:28 UTC, blueorangutan commented
Packaging result: ✔centos7 ✔centos8 ✔debian. JID-2089

2020-09-28 04:42 UTC, rhtyd commented
@blueorangutan test centos7 vmware-67u3

2020-09-28 04:44 UTC, blueorangutan commented
@rhtyd a Trillian-Jenkins test job (centos7 mgmt + vmware-67u3) has been kicked to run smoke tests

2020-09-28 05:48 UTC, harikrishna-patnala commented
@blueorangutan package

2020-09-28 05:49 UTC, blueorangutan commented
@harikrishna-patnala a Jenkins job has been kicked to build packages. I'll keep you posted as I make progress.

2020-09-28 06:22 UTC, blueorangutan commented
Packaging result: ✔centos7 ✔centos8 ✔debian. JID-2091

2020-09-28 17:47 UTC, blueorangutan commented
<b>Trillian test result (tid-2867)</b>
Environment: vmware-67u3 (x2), Advanced Networking with Mgmt server 7
Total time taken: 45529 seconds
Marvin logs: https://github.com/blueorangutan/acs-prs/releases/download/trillian/pr4307-t2867-vmware-67u3.zip
Intermittent failure detected: /marvin/tests/smoke/test_diagnostics.py
Intermittent failure detected: /marvin/tests/smoke/test_internal_lb.py
Intermittent failure detected: /marvin/tests/smoke/test_iso.py
Intermittent failure detected: /marvin/tests/smoke/test_kubernetes_supported_versions.py
Intermittent failure detected: /marvin/tests/smoke/test_loadbalance.py
Intermittent failure detected: /marvin/tests/smoke/test_vpc_redundant.py
Smoke tests completed. 76 look OK, 5 have error(s)
Only failed tests results shown below:


Test | Result | Time (s) | Test File
--- | --- | --- | ---
test_01_internallb_roundrobin_1VPC_3VM_HTTP_port80 | `Failure` | 387.26 | test_internal_lb.py
test_02_internallb_roundrobin_1RVPC_3VM_HTTP_port80 | `Failure` | 548.32 | test_internal_lb.py
test_03_vpc_internallb_haproxy_stats_on_all_interfaces | `Error` | 220.60 | test_internal_lb.py
test_04_rvpc_internallb_haproxy_stats_on_all_interfaces | `Error` | 301.29 | test_internal_lb.py
test_01_ping_in_vr_success | `Failure` | 15.35 | test_diagnostics.py
test_03_ping_in_ssvm_success | `Failure` | 15.34 | test_diagnostics.py
test_05_ping_in_cpvm_success | `Failure` | 15.32 | test_diagnostics.py
test_07_arping_in_vr | `Failure` | 5.15 | test_diagnostics.py
test_08_arping_in_ssvm | `Failure` | 5.16 | test_diagnostics.py
test_09_arping_in_cpvm | `Failure` | 5.16 | test_diagnostics.py
test_13_retrieve_vr_default_files | `Error` | 6.55 | test_diagnostics.py
test_14_retrieve_vr_one_file | `Error` | 13.50 | test_diagnostics.py
test_15_retrieve_ssvm_default_files | `Error` | 13.50 | test_diagnostics.py
test_16_retrieve_ssvm_single_file | `Error` | 13.50 | test_diagnostics.py
test_17_retrieve_cpvm_default_files | `Error` | 13.60 | test_diagnostics.py
test_18_retrieve_cpvm_single_file | `Error` | 13.50 | test_diagnostics.py
test_04_extract_Iso | `Failure` | 6.52 | test_iso.py
test_01_add_delete_kubernetes_supported_version | `Error` | 1807.48 | test_kubernetes_supported_versions.py
test_01_create_redundant_VPC_2tiers_4VMs_4IPs_4PF_ACL | `Failure` | 469.08 | test_vpc_redundant.py
test_05_rvpc_multi_tiers | `Failure` | 225.59 | test_vpc_redundant.py
test_05_rvpc_multi_tiers | `Error` | 225.61 | test_vpc_redundant.py
ContextSuite context=TestVPCRedundancy>:teardown | `Error` | 225.62 | test_vpc_redundant.py

2020-09-29 02:09 UTC, nvazquez commented
@blueorangutan package

2020-09-29 02:10 UTC, blueorangutan commented
@nvazquez a Jenkins job has been kicked to build packages. I'll keep you posted as I make progress.

2020-09-29 02:43 UTC, blueorangutan commented
Packaging result: ✔centos7 ✔centos8 ✔debian. JID-2095

2020-09-29 03:07 UTC, nvazquez commented
@blueorangutan package

2020-09-29 03:48 UTC, nvazquez commented
@blueorangutan package

2020-09-29 03:49 UTC, blueorangutan commented
@nvazquez a Jenkins job has been kicked to build packages. I'll keep you posted as I make progress.

2020-09-29 04:20 UTC, blueorangutan commented
Packaging result: ✔centos7 ✔centos8 ✔debian. JID-2096

2020-09-29 04:31 UTC, nvazquez commented
@blueorangutan test centos7 vmware-67u3

2020-09-29 04:32 UTC, blueorangutan commented
@nvazquez a Trillian-Jenkins test job (centos7 mgmt + vmware-67u3) has been kicked to run smoke tests

2020-09-29 05:35 UTC, nvazquez commented
@blueorangutan package

2020-09-29 05:36 UTC, blueorangutan commented
@nvazquez a Jenkins job has been kicked to build packages. I'll keep you posted as I make progress.

2020-09-29 06:09 UTC, blueorangutan commented
Packaging result: ✔centos7 ✔centos8 ✔debian. JID-2097

2020-09-29 10:34 UTC, harikrishna-patnala commented
@blueorangutan package

2020-09-29 10:35 UTC, blueorangutan commented
@harikrishna-patnala a Jenkins job has been kicked to build packages. I'll keep you posted as I make progress.

2020-09-29 11:07 UTC, blueorangutan commented
Packaging result: ✔centos7 ✔centos8 ✔debian. JID-2104

2020-09-29 15:03 UTC, blueorangutan commented
<b>Trillian test result (tid-2870)</b>
Environment: vmware-67u3 (x2), Advanced Networking with Mgmt server 7
Total time taken: 36216 seconds
Marvin logs: https://github.com/blueorangutan/acs-prs/releases/download/trillian/pr4307-t2870-vmware-67u3.zip
Smoke tests completed. 85 look OK, 0 have error(s)
Only failed tests results shown below:


Test | Result | Time (s) | Test File
--- | --- | --- | ---

2020-09-29 19:17 UTC, DaanHoogland reviewed
some comments and a general observation; `VmwareResource.execute(Startcommand)` is too big and any change in it should be factored out as separate method.

2020-09-30 09:48 UTC, harikrishna-patnala commented
@blueorangutan package

2020-09-30 09:49 UTC, blueorangutan commented
@harikrishna-patnala a Jenkins job has been kicked to build packages. I'll keep you posted as I make progress.

2020-09-30 10:21 UTC, blueorangutan commented
Packaging result: ✔centos7 ✔centos8 ✔debian. JID-2106

2020-10-03 19:19 UTC, rhtyd commented
@blueorangutan package

2020-10-03 19:20 UTC, blueorangutan commented
@rhtyd a Jenkins job has been kicked to build packages. I'll keep you posted as I make progress.

2020-10-03 20:17 UTC, blueorangutan commented
Packaging result: ✔centos7 ✔centos8 ✔debian. JID-2114

2020-10-04 00:07 UTC, rhtyd commented
@blueorangutan test centos7 vmware-67u3

2020-10-04 00:08 UTC, blueorangutan commented
@rhtyd a Trillian-Jenkins test job (centos7 mgmt + vmware-67u3) has been kicked to run smoke tests

2020-10-04 11:21 UTC, blueorangutan commented
<b>Trillian test result (tid-2888)</b>
Environment: vmware-67u3 (x2), Advanced Networking with Mgmt server 7
Total time taken: 38738 seconds
Marvin logs: https://github.com/blueorangutan/acs-prs/releases/download/trillian/pr4307-t2888-vmware-67u3.zip
Intermittent failure detected: /marvin/tests/smoke/test_vpc_redundant.py
Intermittent failure detected: /marvin/tests/smoke/test_vpc_vpn.py
Smoke tests completed. 81 look OK, 1 have error(s)
Only failed tests results shown below:


Test | Result | Time (s) | Test File
--- | --- | --- | ---
test_01_create_redundant_VPC_2tiers_4VMs_4IPs_4PF_ACL | `Failure` | 451.15 | test_vpc_redundant.py

2020-10-04 17:04 UTC, rhtyd commented
@blueorangutan test

2020-10-04 17:04 UTC, blueorangutan commented
@rhtyd a Trillian-Jenkins test job (centos7 mgmt + kvm-centos7) has been kicked to run smoke tests

2020-10-05 11:55 UTC, borisstoyanov commented
@blueorangutan package

2020-10-05 11:56 UTC, blueorangutan commented
@borisstoyanov a Jenkins job has been kicked to build packages. I'll keep you posted as I make progress.

2020-10-05 12:41 UTC, blueorangutan commented
Packaging result: ✔centos7 ✔centos8 ✔debian. JID-2117

2020-10-05 13:35 UTC, borisstoyanov commented
@blueorangutan test centos7 vmware-67u3

2020-10-06 00:18 UTC, blueorangutan commented
<b>Trillian test result (tid-2892)</b>
Environment: vmware-67u3 (x2), Advanced Networking with Mgmt server 7
Total time taken: 36904 seconds
Marvin logs: https://github.com/blueorangutan/acs-prs/releases/download/trillian/pr4307-t2892-vmware-67u3.zip
Intermittent failure detected: /marvin/tests/smoke/test_vpc_redundant.py
Smoke tests completed. 80 look OK, 1 have error(s)
Only failed tests results shown below:


Test | Result | Time (s) | Test File
--- | --- | --- | ---
test_03_create_redundant_VPC_1tier_2VMs_2IPs_2PF_ACL_reboot_routers | `Failure` | 412.51 | test_vpc_redundant.py
test_04_rvpc_network_garbage_collector_nics | `Error` | 3768.72 | test_vpc_redundant.py
test_04_rvpc_network_garbage_collector_nics | `Error` | 3768.75 | test_vpc_redundant.py
test_05_rvpc_multi_tiers | `Error` | 0.01 | test_vpc_redundant.py
ContextSuite context=TestVPCRedundancy>:teardown | `Error` | 0.01 | test_vpc_redundant.py

2020-10-06 06:12 UTC, harikrishna-patnala commented
@blueorangutan package

2020-10-06 06:12 UTC, blueorangutan commented
@harikrishna-patnala a Jenkins job has been kicked to build packages. I'll keep you posted as I make progress.

2020-10-06 06:44 UTC, blueorangutan commented
Packaging result: ✔centos7 ✔centos8 ✔debian. JID-2121

2020-10-07 06:42 UTC, harikrishna-patnala commented
@blueorangutan package

2020-10-07 06:43 UTC, blueorangutan commented
@harikrishna-patnala a Jenkins job has been kicked to build packages. I'll keep you posted as I make progress.

2020-10-07 07:15 UTC, blueorangutan commented
Packaging result: ✔centos7 ✔centos8 ✔debian. JID-2142

2020-10-07 12:18 UTC, borisstoyanov commented
@blueorangutan test centos7 vmware-67u3

2020-10-07 12:20 UTC, blueorangutan commented
@borisstoyanov a Trillian-Jenkins test job (centos7 mgmt + vmware-67u3) has been kicked to run smoke tests

2020-10-07 23:31 UTC, blueorangutan commented
<b>Trillian test result (tid-2907)</b>
Environment: vmware-67u3 (x2), Advanced Networking with Mgmt server 7
Total time taken: 38793 seconds
Marvin logs: https://github.com/blueorangutan/acs-prs/releases/download/trillian/pr4307-t2907-vmware-67u3.zip
Intermittent failure detected: /marvin/tests/smoke/test_vpc_redundant.py
Smoke tests completed. 84 look OK, 1 have error(s)
Only failed tests results shown below:


Test | Result | Time (s) | Test File
--- | --- | --- | ---
test_01_create_redundant_VPC_2tiers_4VMs_4IPs_4PF_ACL | `Failure` | 402.70 | test_vpc_redundant.py
test_03_create_redundant_VPC_1tier_2VMs_2IPs_2PF_ACL_reboot_routers | `Failure` | 401.02 | test_vpc_redundant.py

2020-10-08 03:31 UTC, harikrishna-patnala commented
@blueorangutan package

2020-10-08 03:32 UTC, blueorangutan commented
@harikrishna-patnala a Jenkins job has been kicked to build packages. I'll keep you posted as I make progress.

2020-10-08 04:03 UTC, blueorangutan commented
Packaging result: ✔centos7 ✔centos8 ✔debian. JID-2149

2020-10-08 17:15 UTC, DaanHoogland commented
@blueorangutan test centos7 vmware-67u3

2020-10-08 17:16 UTC, blueorangutan commented
@DaanHoogland a Trillian-Jenkins test job (centos7 mgmt + vmware-67u3) has been kicked to run smoke tests

2020-10-09 00:13 UTC, harikrishna-patnala commented
@blueorangutan package

2020-10-09 00:14 UTC, blueorangutan commented
@harikrishna-patnala a Jenkins job has been kicked to build packages. I'll keep you posted as I make progress.

2020-10-09 00:47 UTC, blueorangutan commented
Packaging result: ✔centos7 ✔centos8 ✔debian. JID-2151

2020-10-09 02:52 UTC, nvazquez commented
@blueorangutan package

2020-10-09 02:53 UTC, blueorangutan commented
@nvazquez a Jenkins job has been kicked to build packages. I'll keep you posted as I make progress.

2020-10-09 03:13 UTC, blueorangutan commented
<b>Trillian test result (tid-2915)</b>
Environment: vmware-67u3 (x2), Advanced Networking with Mgmt server 7
Total time taken: 34044 seconds
Marvin logs: https://github.com/blueorangutan/acs-prs/releases/download/trillian/pr4307-t2915-vmware-67u3.zip
Intermittent failure detected: /marvin/tests/smoke/test_vpc_vpn.py
Smoke tests completed. 82 look OK, 0 have error(s)
Only failed tests results shown below:


Test | Result | Time (s) | Test File
--- | --- | --- | ---

2020-10-09 03:25 UTC, blueorangutan commented
Packaging result: ✔centos7 ✔centos8 ✔debian. JID-2152

2020-10-09 14:58 UTC, nvazquez commented
@blueorangutan test centos7 vmware-67u3

2020-10-09 15:00 UTC, blueorangutan commented
@nvazquez a Trillian-Jenkins test job (centos7 mgmt + vmware-67u3) has been kicked to run smoke tests

2020-10-10 02:44 UTC, blueorangutan commented
<b>Trillian test result (tid-2921)</b>
Environment: vmware-67u3 (x2), Advanced Networking with Mgmt server 7
Total time taken: 40704 seconds
Marvin logs: https://github.com/blueorangutan/acs-prs/releases/download/trillian/pr4307-t2921-vmware-67u3.zip
Intermittent failure detected: /marvin/tests/smoke/test_kubernetes_clusters.py
Intermittent failure detected: /marvin/tests/smoke/test_vpc_redundant.py
Smoke tests completed. 79 look OK, 2 have error(s)
Only failed tests results shown below:


Test | Result | Time (s) | Test File
--- | --- | --- | ---
test_03_deploy_and_upgrade_kubernetes_cluster | `Failure` | 790.10 | test_kubernetes_clusters.py
test_03_create_redundant_VPC_1tier_2VMs_2IPs_2PF_ACL_reboot_routers | `Failure` | 410.03 | test_vpc_redundant.py
test_05_rvpc_multi_tiers | `Error` | 323.67 | test_vpc_redundant.py
test_05_rvpc_multi_tiers | `Error` | 323.70 | test_vpc_redundant.py
ContextSuite context=TestVPCRedundancy>:teardown | `Error` | 323.73 | test_vpc_redundant.py

2020-10-12 03:53 UTC, rhtyd commented
@harikrishna-patnala @nvazquez can you fix conflicts and kick test matrix? Thnx

2020-10-12 05:32 UTC, harikrishna-patnala commented
@blueorangutan package

2020-10-12 05:33 UTC, blueorangutan commented
@harikrishna-patnala a Jenkins job has been kicked to build packages. I'll keep you posted as I make progress.

2020-10-12 06:04 UTC, blueorangutan commented
Packaging result: ✔centos7 ✔centos8 ✔debian. JID-2157

2020-10-12 06:43 UTC, borisstoyanov commented
@blueorangutan test centos7 vmware-67u3

2020-10-12 06:44 UTC, blueorangutan commented
@borisstoyanov a Trillian-Jenkins test job (centos7 mgmt + vmware-67u3) has been kicked to run smoke tests

2020-10-12 10:22 UTC, rhtyd commented
@blueorangutan package

2020-10-12 10:23 UTC, blueorangutan commented
@rhtyd a Jenkins job has been kicked to build packages. I'll keep you posted as I make progress.

2020-10-12 11:34 UTC, blueorangutan commented
Packaging result: ✖centos7 ✖centos8 ✔debian. JID-2159

2020-10-13 06:01 UTC, borisstoyanov commented
@blueorangutan package

2020-10-13 06:02 UTC, blueorangutan commented
@borisstoyanov a Jenkins job has been kicked to build packages. I'll keep you posted as I make progress.

2020-10-13 06:34 UTC, blueorangutan commented
Packaging result: ✔centos7 ✔centos8 ✔debian. JID-2164

2020-10-13 19:24 UTC, nvazquez commented
@blueorangutan package

2020-10-13 19:25 UTC, blueorangutan commented
@nvazquez a Jenkins job has been kicked to build packages. I'll keep you posted as I make progress.

2020-10-13 19:58 UTC, blueorangutan commented
Packaging result: ✔centos7 ✔centos8 ✔debian. JID-2170

2020-10-13 22:00 UTC, nvazquez commented
@blueorangutan test centos7 vmware-67u3

2020-10-14 01:44 UTC, nvazquez commented
@blueorangutan test centos7 vmware-67u3

2020-10-14 10:06 UTC, rhtyd commented
@nvazquez @harikrishna-patnala please look at Travis tests too after they complete (just rekicked few failed jobs) and ensure they pass, thanks.

2020-10-15 06:23 UTC, borisstoyanov commented
@blueorangutan package

2020-10-15 06:24 UTC, blueorangutan commented
@borisstoyanov a Jenkins job has been kicked to build packages. I'll keep you posted as I make progress.

2020-10-15 07:02 UTC, blueorangutan commented
Packaging result: ✔centos7 ✔centos8 ✔debian. JID-2183

2020-10-15 16:29 UTC, nvazquez commented
@blueorangutan package

2020-10-15 16:30 UTC, blueorangutan commented
@nvazquez a Jenkins job has been kicked to build packages. I'll keep you posted as I make progress.

2020-10-15 17:03 UTC, blueorangutan commented
Packaging result: ✔centos7 ✔centos8 ✔debian. JID-2188

2020-10-15 22:08 UTC, nvazquez commented
@blueorangutan test centos7 vmware-67u3

2020-10-15 22:09 UTC, blueorangutan commented
@nvazquez a Trillian-Jenkins test job (centos7 mgmt + vmware-67u3) has been kicked to run smoke tests

2020-10-16 04:14 UTC, nvazquez commented
@blueorangutan package

2020-10-16 04:15 UTC, blueorangutan commented
@nvazquez a Jenkins job has been kicked to build packages. I'll keep you posted as I make progress.

2020-10-16 05:06 UTC, blueorangutan commented
Packaging result: ✔centos7 ✔centos8 ✔debian. JID-2193

2020-10-17 20:48 UTC, rhtyd commented
@blueorangutan package

2020-10-17 20:50 UTC, rhtyd commented
@blueorangutan package

2020-10-17 20:52 UTC, blueorangutan commented
@rhtyd a Jenkins job has been kicked to build packages. I'll keep you posted as I make progress.

2020-10-17 21:40 UTC, blueorangutan commented
Packaging result: ✔centos7 ✔centos8 ✔debian. JID-2202

2020-10-17 22:41 UTC, rhtyd commented
@blueorangutan test matrix

2020-10-17 22:41 UTC, blueorangutan commented
@rhtyd a Trillian-Jenkins matrix job (centos6 mgmt + xs71, centos7 mgmt + vmware65, centos7 mgmt + kvmcentos7) has been kicked to run smoke tests

2020-10-19 03:11 UTC, nvazquez commented
@blueorangutan package

2020-10-19 03:12 UTC, blueorangutan commented
@nvazquez a Jenkins job has been kicked to build packages. I'll keep you posted as I make progress.

2020-10-19 03:45 UTC, blueorangutan commented
Packaging result: ✔centos7 ✔centos8 ✔debian. JID-2203

2020-10-19 10:18 UTC, harikrishna-patnala commented
@blueorangutan package

2020-10-19 10:18 UTC, blueorangutan commented
@harikrishna-patnala a Jenkins job has been kicked to build packages. I'll keep you posted as I make progress.

2020-10-19 10:51 UTC, blueorangutan commented
Packaging result: ✔centos7 ✔centos8 ✔debian. JID-2206

2020-10-20 06:03 UTC, nvazquez commented
@blueorangutan package

2020-10-20 06:04 UTC, blueorangutan commented
@nvazquez a Jenkins job has been kicked to build packages. I'll keep you posted as I make progress.

2020-10-20 06:37 UTC, blueorangutan commented
Packaging result: ✔centos7 ✔centos8 ✔debian. JID-2208

2020-10-20 22:58 UTC, nvazquez commented
@blueorangutan package

2020-10-21 06:47 UTC, DaanHoogland requested changes

2020-10-21 06:47 UTC, DaanHoogland commented on test/integration/smoke/test_storage_policy.py
> +        cls.cleanup = [cls.network_offering]
this will not be cleaned, needs to be something like below
```suggestion
        cls._cleanup.append(cls.network_offering)
```

2020-10-21 06:47 UTC, DaanHoogland commented on test/integration/smoke/test_storage_policy.py
> +            cleanup_resources(cls.apiclient, cls.cleanup)
```suggestion
            cleanup_resources(cls.apiclient, reverved(cls._cleanup))
```

2020-10-21 06:47 UTC, DaanHoogland commented on test/integration/smoke/test_storage_policy.py
> +        self.cleanup = [self.account]
would be a good habbit to use
```suggestion
        self.cleanup = []
        self.cleanup.append(self.account)
```

2020-10-21 06:47 UTC, DaanHoogland commented on test/integration/smoke/test_storage_policy.py
> +            cleanup_resources(self.apiclient, self.cleanup)
also a good habit;
```suggestion
            cleanup_resources(self.apiclient, reversed(self.cleanup))
```

2020-10-21 06:47 UTC, DaanHoogland commented on test/integration/smoke/test_storage_policy.py
> +        cmd = create
```suggestion
        cmd = create

```

2020-10-21 06:47 UTC, DaanHoogland commented on test/integration/smoke/test_storage_policy.py
> +        tags=[
isn't a tag for vmware in order?

2020-10-21 06:47 UTC, DaanHoogland commented on test/integration/smoke/test_storage_policy.py
> +        # 8. Detach the volume from our VM
sensible comments, but I would like to see this be partitioned into methods of which the names reflect these comments. this method is long and thus rather hard to understand. also it is hard to check if it does what it says on the tin, certainly after a few rounds of maintenance.

2020-10-21 07:35 UTC, andrijapanicsb commented
@blueorangutan package

2020-10-21 07:36 UTC, blueorangutan commented
@andrijapanicsb a Jenkins job has been kicked to build packages. I'll keep you posted as I make progress.

2020-10-21 07:40 UTC, DaanHoogland commented
@blueorangutan package

2020-10-21 07:41 UTC, blueorangutan commented
@DaanHoogland a Jenkins job has been kicked to build packages. I'll keep you posted as I make progress.

2020-10-21 07:45 UTC, blueorangutan commented
Packaging result: ✖centos7 ✖centos8 ✖debian. JID-2242

2020-10-21 07:46 UTC, DaanHoogland commented
@blueorangutan package

2020-10-21 07:46 UTC, blueorangutan commented
@DaanHoogland a Jenkins job has been kicked to build packages. I'll keep you posted as I make progress.

2020-10-21 08:23 UTC, blueorangutan commented
Packaging result: ✔centos7 ✔centos8 ✔debian. JID-2243

2020-10-21 14:48 UTC, nvazquez commented
@blueorangutan package

2020-10-21 14:50 UTC, blueorangutan commented
@nvazquez a Jenkins job has been kicked to build packages. I'll keep you posted as I make progress.

2020-10-21 15:21 UTC, blueorangutan commented
Packaging result: ✔centos7 ✔centos8 ✔debian. JID-2253

2020-10-21 16:38 UTC, andrijapanicsb commented
@blueorangutan test matrix

2020-10-21 16:39 UTC, blueorangutan commented
@andrijapanicsb a Trillian-Jenkins matrix job (centos6 mgmt + xs71, centos7 mgmt + vmware65, centos7 mgmt + kvmcentos7) has been kicked to run smoke tests

2020-10-21 16:40 UTC, andrijapanicsb commented
LGTM 
(after the  extensive functional testing side)

2020-10-21 16:42 UTC, alexandremattioli commented
LGTM

2020-10-21 16:43 UTC, andrijapanicsb commented
@blueorangutan test centos7 vmware-67u3

2020-10-21 16:50 UTC, andrijapanicsb commented
@blueorangutan test centos7 vmware-67u3

2020-10-21 16:52 UTC, blueorangutan commented
@andrijapanicsb a Trillian-Jenkins test job (centos7 mgmt + vmware-67u3) has been kicked to run smoke tests

2020-10-21 21:01 UTC, blueorangutan commented
<b>Trillian test result (tid-3039)</b>
Environment: vmware-65u2 (x2), Advanced Networking with Mgmt server 7
Total time taken: 14006 seconds
Marvin logs: https://github.com/blueorangutan/acs-prs/releases/download/trillian/pr4307-t3039-vmware-65u2.zip
Intermittent failure detected: /marvin/tests/smoke/test_accounts.py
Intermittent failure detected: /marvin/tests/smoke/test_affinity_groups_projects.py
Intermittent failure detected: /marvin/tests/smoke/test_async_job.py
Intermittent failure detected: /marvin/tests/smoke/test_deploy_vgpu_enabled_vm.py
Intermittent failure detected: /marvin/tests/smoke/test_deploy_vm_iso.py
Intermittent failure detected: /marvin/tests/smoke/test_deploy_vms_with_varied_deploymentplanners.py
Intermittent failure detected: /marvin/tests/smoke/test_deploy_vm_with_userdata.py
Intermittent failure detected: /marvin/tests/smoke/test_diagnostics.py
Intermittent failure detected: /marvin/tests/smoke/test_domain_service_offerings.py
Intermittent failure detected: /marvin/tests/smoke/test_human_readable_logs.py
Intermittent failure detected: /marvin/tests/smoke/test_internal_lb.py
Intermittent failure detected: /marvin/tests/smoke/test_kubernetes_clusters.py
Intermittent failure detected: /marvin/tests/smoke/test_list_ids_parameter.py
Intermittent failure detected: /marvin/tests/smoke/test_loadbalance.py
Intermittent failure detected: /marvin/tests/smoke/test_metrics_api.py
Intermittent failure detected: /marvin/tests/smoke/test_multipleips_per_nic.py
Intermittent failure detected: /marvin/tests/smoke/test_nested_virtualization.py
Intermittent failure detected: /marvin/tests/smoke/test_network_acl.py
Intermittent failure detected: /marvin/tests/smoke/test_network.py
Intermittent failure detected: /marvin/tests/smoke/test_nic_adapter_type.py
Intermittent failure detected: /marvin/tests/smoke/test_password_server.py
Intermittent failure detected: /marvin/tests/smoke/test_portforwardingrules.py
Intermittent failure detected: /marvin/tests/smoke/test_privategw_acl.py
Intermittent failure detected: /marvin/tests/smoke/test_projects.py
Intermittent failure detected: /marvin/tests/smoke/test_reset_vm_on_reboot.py
Intermittent failure detected: /marvin/tests/smoke/test_resource_accounting.py
Intermittent failure detected: /marvin/tests/smoke/test_router_dhcphosts.py
Intermittent failure detected: /marvin/tests/smoke/test_router_dns.py
Intermittent failure detected: /marvin/tests/smoke/test_router_dnsservice.py
Intermittent failure detected: /marvin/tests/smoke/test_routers_iptables_default_policy.py
Intermittent failure detected: /marvin/tests/smoke/test_routers_network_ops.py
Intermittent failure detected: /marvin/tests/smoke/test_routers.py
Intermittent failure detected: /marvin/tests/smoke/test_service_offerings.py
Intermittent failure detected: /marvin/tests/smoke/test_snapshots.py
Intermittent failure detected: /marvin/tests/smoke/test_storage_policy.py
Intermittent failure detected: /marvin/tests/smoke/test_templates.py
Intermittent failure detected: /marvin/tests/smoke/test_vpc_redundant.py
Intermittent failure detected: /marvin/tests/smoke/test_vpc_router_nics.py
Intermittent failure detected: /marvin/tests/smoke/test_vpc_vpn.py
Smoke tests completed. 48 look OK, 38 have error(s)
Only failed tests results shown below:


Test | Result | Time (s) | Test File
--- | --- | --- | ---
ContextSuite context=TestAccounts>:setup | `Error` | 0.00 | test_accounts.py
ContextSuite context=TestAddVmToSubDomain>:setup | `Error` | 0.00 | test_accounts.py
ContextSuite context=TestDomainForceRemove>:setup | `Error` | 0.00 | test_accounts.py
ContextSuite context=TestRemoveUserFromAccount>:setup | `Error` | 5.83 | test_accounts.py
ContextSuite context=TestTemplateHierarchy>:setup | `Error` | 7.11 | test_accounts.py
ContextSuite context=TestDeployVmWithAffinityGroup>:setup | `Error` | 0.00 | test_affinity_groups_projects.py
ContextSuite context=TestAsyncJob>:setup | `Error` | 0.00 | test_async_job.py
test_3d_gpu_support | `Error` | 1.15 | test_deploy_vgpu_enabled_vm.py
test_deploy_vgpu_enabled_vm | `Error` | 1.15 | test_deploy_vgpu_enabled_vm.py
ContextSuite context=TestDeployVMFromISO>:setup | `Error` | 0.00 | test_deploy_vm_iso.py
ContextSuite context=TestInternalLb>:setup | `Error` | 0.00 | test_internal_lb.py
ContextSuite context=TestRemoteDiagnostics>:setup | `Error` | 0.00 | test_diagnostics.py
ContextSuite context=TestDeployVmWithVariedPlanners>:setup | `Error` | 0.00 | test_deploy_vms_with_varied_deploymentplanners.py
ContextSuite context=TestDeployVmWithUserData>:setup | `Error` | 0.00 | test_deploy_vm_with_userdata.py
ContextSuite context=TestDomainsServiceOfferings>:setup | `Error` | 3.68 | test_domain_service_offerings.py
ContextSuite context=TestKubernetesCluster>:setup | `Error` | 0.00 | test_kubernetes_clusters.py
ContextSuite context=TestListIdsParams>:setup | `Error` | 0.00 | test_list_ids_parameter.py
ContextSuite context=TestLoadBalance>:setup | `Error` | 0.00 | test_loadbalance.py
test_list_clusters_metrics | `Error` | 0.27 | test_metrics_api.py
test_list_hosts_metrics | `Error` | 0.24 | test_metrics_api.py
test_list_infrastructure_metrics | `Error` | 0.24 | test_metrics_api.py
test_list_pstorage_metrics | `Error` | 0.22 | test_metrics_api.py
test_list_vms_metrics | `Error` | 0.21 | test_metrics_api.py
test_list_volumes_metrics | `Error` | 0.29 | test_metrics_api.py
test_list_zones_metrics | `Error` | 0.27 | test_metrics_api.py
test_nic_secondaryip_add_remove | `Error` | 0.09 | test_multipleips_per_nic.py
ContextSuite context=TestNestedVirtualization>:setup | `Error` | 0.00 | test_nested_virtualization.py
ContextSuite context=TestNetworkACL>:setup | `Error` | 0.00 | test_network_acl.py
test_delete_account | `Error` | 0.11 | test_network.py
ContextSuite context=TestL2Networks>:setup | `Error` | 0.87 | test_network.py
ContextSuite context=TestPortForwarding>:setup | `Error` | 0.96 | test_network.py
ContextSuite context=TestPublicIP>:setup | `Error` | 1.93 | test_network.py
test_reboot_router | `Error` | 0.09 | test_network.py
test_releaseIP | `Error` | 0.10 | test_network.py
ContextSuite context=TestRouterRules>:setup | `Error` | 0.21 | test_network.py
ContextSuite context=TestAdapterTypeForNic>:setup | `Error` | 0.00 | test_nic_adapter_type.py
ContextSuite context=TestIsolatedNetworksPasswdServer>:setup | `Error` | 0.00 | test_password_server.py
ContextSuite context=TestPortForwardingRules>:setup | `Error` | 0.00 | test_portforwardingrules.py
ContextSuite context=TestPrivateGwACL>:setup | `Error` | 0.00 | test_privategw_acl.py
ContextSuite context=TestProjectSuspendActivate>:setup | `Error` | 7.48 | test_projects.py
ContextSuite context=TestResetVmOnReboot>:setup | `Error` | 0.00 | test_reset_vm_on_reboot.py
ContextSuite context=TestRAMCPUResourceAccounting>:setup | `Error` | 0.00 | test_resource_accounting.py
ContextSuite context=TestRouterDHCPHosts>:setup | `Error` | 0.00 | test_router_dhcphosts.py
ContextSuite context=TestRouterDHCPOpts>:setup | `Error` | 0.00 | test_router_dhcphosts.py
ContextSuite context=TestRouterDns>:setup | `Error` | 0.00 | test_router_dns.py
ContextSuite context=TestRouterDnsService>:setup | `Error` | 0.00 | test_router_dnsservice.py
ContextSuite context=TestRouterIpTablesPolicies>:setup | `Error` | 0.00 | test_routers_iptables_default_policy.py
ContextSuite context=TestVPCIpTablesPolicies>:setup | `Error` | 0.00 | test_routers_iptables_default_policy.py
ContextSuite context=TestIsolatedNetworks>:setup | `Error` | 0.00 | test_routers_network_ops.py
ContextSuite context=TestRedundantIsolateNetworks>:setup | `Error` | 0.00 | test_routers_network_ops.py
ContextSuite context=TestRouterServices>:setup | `Error` | 0.00 | test_routers.py
ContextSuite context=TestServiceOfferings>:setup | `Error` | 0.19 | test_service_offerings.py
ContextSuite context=TestSnapshotRootDisk>:setup | `Error` | 0.00 | test_snapshots.py
ContextSuite context=TestVMWareStoragePolicies>:setup | `Error` | 0.00 | test_storage_policy.py
test_0 [...]

2020-10-21 21:10 UTC, blueorangutan commented
<b>Trillian test result (tid-3040)</b>
Environment: vmware-67u3 (x2), Advanced Networking with Mgmt server 7
Total time taken: 13762 seconds
Marvin logs: https://github.com/blueorangutan/acs-prs/releases/download/trillian/pr4307-t3040-vmware-67u3.zip
Intermittent failure detected: /marvin/tests/smoke/test_accounts.py
Intermittent failure detected: /marvin/tests/smoke/test_affinity_groups_projects.py
Intermittent failure detected: /marvin/tests/smoke/test_async_job.py
Intermittent failure detected: /marvin/tests/smoke/test_deploy_vgpu_enabled_vm.py
Intermittent failure detected: /marvin/tests/smoke/test_deploy_vm_iso.py
Intermittent failure detected: /marvin/tests/smoke/test_deploy_vms_with_varied_deploymentplanners.py
Intermittent failure detected: /marvin/tests/smoke/test_deploy_vm_with_userdata.py
Intermittent failure detected: /marvin/tests/smoke/test_diagnostics.py
Intermittent failure detected: /marvin/tests/smoke/test_domain_service_offerings.py
Intermittent failure detected: /marvin/tests/smoke/test_internal_lb.py
Intermittent failure detected: /marvin/tests/smoke/test_kubernetes_clusters.py
Intermittent failure detected: /marvin/tests/smoke/test_list_ids_parameter.py
Intermittent failure detected: /marvin/tests/smoke/test_loadbalance.py
Intermittent failure detected: /marvin/tests/smoke/test_metrics_api.py
Intermittent failure detected: /marvin/tests/smoke/test_multipleips_per_nic.py
Intermittent failure detected: /marvin/tests/smoke/test_nested_virtualization.py
Intermittent failure detected: /marvin/tests/smoke/test_network_acl.py
Intermittent failure detected: /marvin/tests/smoke/test_network.py
Intermittent failure detected: /marvin/tests/smoke/test_nic_adapter_type.py
Intermittent failure detected: /marvin/tests/smoke/test_password_server.py
Intermittent failure detected: /marvin/tests/smoke/test_portforwardingrules.py
Intermittent failure detected: /marvin/tests/smoke/test_privategw_acl.py
Intermittent failure detected: /marvin/tests/smoke/test_projects.py
Intermittent failure detected: /marvin/tests/smoke/test_reset_vm_on_reboot.py
Intermittent failure detected: /marvin/tests/smoke/test_resource_accounting.py
Intermittent failure detected: /marvin/tests/smoke/test_router_dhcphosts.py
Intermittent failure detected: /marvin/tests/smoke/test_router_dns.py
Intermittent failure detected: /marvin/tests/smoke/test_router_dnsservice.py
Intermittent failure detected: /marvin/tests/smoke/test_routers_iptables_default_policy.py
Intermittent failure detected: /marvin/tests/smoke/test_routers_network_ops.py
Intermittent failure detected: /marvin/tests/smoke/test_routers.py
Intermittent failure detected: /marvin/tests/smoke/test_service_offerings.py
Intermittent failure detected: /marvin/tests/smoke/test_snapshots.py
Intermittent failure detected: /marvin/tests/smoke/test_storage_policy.py
Intermittent failure detected: /marvin/tests/smoke/test_templates.py
Intermittent failure detected: /marvin/tests/smoke/test_vpc_redundant.py
Intermittent failure detected: /marvin/tests/smoke/test_vpc_router_nics.py
Intermittent failure detected: /marvin/tests/smoke/test_vpc_vpn.py
Smoke tests completed. 48 look OK, 38 have error(s)
Only failed tests results shown below:


Test | Result | Time (s) | Test File
--- | --- | --- | ---
ContextSuite context=TestAccounts>:setup | `Error` | 0.00 | test_accounts.py
ContextSuite context=TestAddVmToSubDomain>:setup | `Error` | 0.00 | test_accounts.py
ContextSuite context=TestDomainForceRemove>:setup | `Error` | 0.00 | test_accounts.py
ContextSuite context=TestRemoveUserFromAccount>:setup | `Error` | 5.84 | test_accounts.py
ContextSuite context=TestTemplateHierarchy>:setup | `Error` | 7.12 | test_accounts.py
ContextSuite context=TestDeployVmWithAffinityGroup>:setup | `Error` | 0.00 | test_affinity_groups_projects.py
ContextSuite context=TestAsyncJob>:setup | `Error` | 0.00 | test_async_job.py
test_3d_gpu_support | `Error` | 1.10 | test_deploy_vgpu_enabled_vm.py
test_deploy_vgpu_enabled_vm | `Error` | 1.13 | test_deploy_vgpu_enabled_vm.py
ContextSuite context=TestDeployVMFromISO>:setup | `Error` | 0.00 | test_deploy_vm_iso.py
ContextSuite context=TestInternalLb>:setup | `Error` | 0.00 | test_internal_lb.py
ContextSuite context=TestRemoteDiagnostics>:setup | `Error` | 0.00 | test_diagnostics.py
ContextSuite context=TestDeployVmWithVariedPlanners>:setup | `Error` | 0.00 | test_deploy_vms_with_varied_deploymentplanners.py
ContextSuite context=TestDeployVmWithUserData>:setup | `Error` | 0.00 | test_deploy_vm_with_userdata.py
ContextSuite context=TestDomainsServiceOfferings>:setup | `Error` | 3.70 | test_domain_service_offerings.py
ContextSuite context=TestKubernetesCluster>:setup | `Error` | 0.00 | test_kubernetes_clusters.py
ContextSuite context=TestListIdsParams>:setup | `Error` | 0.00 | test_list_ids_parameter.py
ContextSuite context=TestLoadBalance>:setup | `Error` | 0.00 | test_loadbalance.py
test_list_clusters_metrics | `Error` | 0.23 | test_metrics_api.py
test_list_hosts_metrics | `Error` | 0.23 | test_metrics_api.py
test_list_infrastructure_metrics | `Error` | 0.22 | test_metrics_api.py
test_list_pstorage_metrics | `Error` | 0.22 | test_metrics_api.py
test_list_vms_metrics | `Error` | 0.22 | test_metrics_api.py
test_list_volumes_metrics | `Error` | 0.24 | test_metrics_api.py
test_list_zones_metrics | `Error` | 0.23 | test_metrics_api.py
test_nic_secondaryip_add_remove | `Error` | 0.10 | test_multipleips_per_nic.py
ContextSuite context=TestNestedVirtualization>:setup | `Error` | 0.00 | test_nested_virtualization.py
ContextSuite context=TestNetworkACL>:setup | `Error` | 0.00 | test_network_acl.py
test_delete_account | `Error` | 0.10 | test_network.py
ContextSuite context=TestL2Networks>:setup | `Error` | 0.94 | test_network.py
ContextSuite context=TestPortForwarding>:setup | `Error` | 1.04 | test_network.py
ContextSuite context=TestPublicIP>:setup | `Error` | 1.89 | test_network.py
test_reboot_router | `Error` | 0.09 | test_network.py
test_releaseIP | `Error` | 0.09 | test_network.py
ContextSuite context=TestRouterRules>:setup | `Error` | 0.17 | test_network.py
ContextSuite context=TestAdapterTypeForNic>:setup | `Error` | 0.00 | test_nic_adapter_type.py
ContextSuite context=TestIsolatedNetworksPasswdServer>:setup | `Error` | 0.00 | test_password_server.py
ContextSuite context=TestPortForwardingRules>:setup | `Error` | 0.00 | test_portforwardingrules.py
ContextSuite context=TestPrivateGwACL>:setup | `Error` | 0.00 | test_privategw_acl.py
ContextSuite context=TestProjectSuspendActivate>:setup | `Error` | 7.51 | test_projects.py
ContextSuite context=TestResetVmOnReboot>:setup | `Error` | 0.00 | test_reset_vm_on_reboot.py
ContextSuite context=TestRAMCPUResourceAccounting>:setup | `Error` | 0.00 | test_resource_accounting.py
ContextSuite context=TestRouterDHCPHosts>:setup | `Error` | 0.00 | test_router_dhcphosts.py
ContextSuite context=TestRouterDHCPOpts>:setup | `Error` | 0.00 | test_router_dhcphosts.py
ContextSuite context=TestRouterDns>:setup | `Error` | 0.00 | test_router_dns.py
ContextSuite context=TestRouterDnsService>:setup | `Error` | 0.00 | test_router_dnsservice.py
ContextSuite context=TestRouterIpTablesPolicies>:setup | `Error` | 0.00 | test_routers_iptables_default_policy.py
ContextSuite context=TestVPCIpTablesPolicies>:setup | `Error` | 0.00 | test_routers_iptables_default_policy.py
ContextSuite context=TestIsolatedNetworks>:setup | `Error` | 0.00 | test_routers_network_ops.py
ContextSuite context=TestRedundantIsolateNetworks>:setup | `Error` | 0.00 | test_routers_network_ops.py
ContextSuite context=TestRouterServices>:setup | `Error` | 0.00 | test_routers.py
ContextSuite context=TestServiceOfferings>:setup | `Error` | 0.18 | test_service_offerings.py
ContextSuite context=TestSnapshotRootDisk>:setup | `Error` | 0.00 | test_snapshots.py
ContextSuite context=TestVMWareStoragePolicies>:setup | `Error` | 0.00 | test_storage_policy.py
test_02_1_create_template_with_checksum_sha1_negative | `Error` | 0.08 | test_templat [...]

2020-10-22 02:21 UTC, blueorangutan commented
<b>Trillian test result (tid-3038)</b>
Environment: kvm-centos7 (x2), Advanced Networking with Mgmt server 7
Total time taken: 33007 seconds
Marvin logs: https://github.com/blueorangutan/acs-prs/releases/download/trillian/pr4307-t3038-kvm-centos7.zip
Intermittent failure detected: /marvin/tests/smoke/test_snapshots.py
Intermittent failure detected: /marvin/tests/smoke/test_storage_policy.py
Intermittent failure detected: /marvin/tests/smoke/test_usage.py
Smoke tests completed. 83 look OK, 3 have error(s)
Only failed tests results shown below:


Test | Result | Time (s) | Test File
--- | --- | --- | ---
test_02_list_snapshots_with_removed_data_store | `Error` | 10.90 | test_snapshots.py
ContextSuite context=TestVMWareStoragePolicies>:teardown | `Error` | 1.54 | test_storage_policy.py
test_01_volume_usage | `Error` | 125.06 | test_usage.py

2020-10-22 04:27 UTC, nvazquez commented
@blueorangutan package

2020-10-22 04:28 UTC, blueorangutan commented
@nvazquez a Jenkins job has been kicked to build packages. I'll keep you posted as I make progress.

2020-10-22 05:00 UTC, blueorangutan commented
Packaging result: ✔centos7 ✔centos8 ✔debian. JID-2257

2020-10-22 05:07 UTC, nvazquez commented
@blueorangutan test centos7 vmware-67u3

2020-10-22 05:08 UTC, blueorangutan commented
@nvazquez a Trillian-Jenkins test job (centos7 mgmt + vmware-67u3) has been kicked to run smoke tests

2020-10-22 12:03 UTC, DaanHoogland commented
@blueorangutan test centos6 xenserver-71

2020-10-22 12:05 UTC, blueorangutan commented
@DaanHoogland a Trillian-Jenkins test job (centos6 mgmt + xenserver-71) has been kicked to run smoke tests

2020-10-22 13:29 UTC, DaanHoogland commented
@blueorangutan test centos6 xenserver-71

2020-10-22 13:31 UTC, blueorangutan commented
@DaanHoogland a Trillian-Jenkins test job (centos6 mgmt + xenserver-71) has been kicked to run smoke tests

2020-10-22 17:16 UTC, andrijapanicsb approved these changes

2020-10-22 19:37 UTC, blueorangutan commented
<b>Trillian test result (tid-3042)</b>
Environment: vmware-67u3 (x2), Advanced Networking with Mgmt server 7
Total time taken: 50431 seconds
Marvin logs: https://github.com/blueorangutan/acs-prs/releases/download/trillian/pr4307-t3042-vmware-67u3.zip
Intermittent failure detected: /marvin/tests/smoke/test_diagnostics.py
Intermittent failure detected: /marvin/tests/smoke/test_kubernetes_clusters.py
Intermittent failure detected: /marvin/tests/smoke/test_outofbandmanagement.py
Intermittent failure detected: /marvin/tests/smoke/test_storage_policy.py
Intermittent failure detected: /marvin/tests/smoke/test_templates.py
Intermittent failure detected: /marvin/tests/smoke/test_volumes.py
Smoke tests completed. 82 look OK, 3 have error(s)
Only failed tests results shown below:


Test | Result | Time (s) | Test File
--- | --- | --- | ---
ContextSuite context=TestKubernetesCluster>:setup | `Error` | 0.00 | test_kubernetes_clusters.py
test_01_import_storage_policies | `Error` | 3.33 | test_storage_policy.py
ContextSuite context=TestVMWareStoragePolicies>:teardown | `Error` | 4.43 | test_storage_policy.py
test_02_1_create_template_with_checksum_sha1_negative | `Error` | 0.07 | test_templates.py
test_02_create_template_with_checksum_sha1 | `Error` | 0.06 | test_templates.py
test_03_1_create_template_with_checksum_sha256_negative | `Error` | 0.06 | test_templates.py
test_03_create_template_with_checksum_sha256 | `Error` | 0.07 | test_templates.py
test_04_1_create_template_with_checksum_md5_negative | `Error` | 0.06 | test_templates.py
test_04_create_template_with_checksum_md5 | `Error` | 0.06 | test_templates.py
test_05_create_template_with_no_checksum | `Error` | 0.06 | test_templates.py

2020-10-22 19:39 UTC, DaanHoogland commented
@blueorangutan test centos7 xenserver-71

2020-10-22 19:40 UTC, blueorangutan commented
@DaanHoogland a Trillian-Jenkins test job (centos7 mgmt + xenserver-71) has been kicked to run smoke tests

2020-10-22 20:15 UTC, nvazquez commented
@blueorangutan package

2020-10-22 20:16 UTC, blueorangutan commented
@nvazquez a Jenkins job has been kicked to build packages. I'll keep you posted as I make progress.

2020-10-22 20:48 UTC, blueorangutan commented
Packaging result: ✔centos7 ✔centos8 ✔debian. JID-2266

2020-10-22 20:49 UTC, nvazquez commented
@blueorangutan test centos7 vmware-67u3

2020-10-22 20:51 UTC, blueorangutan commented
@nvazquez a Trillian-Jenkins test job (centos7 mgmt + vmware-67u3) has been kicked to run smoke tests

2020-10-23 01:08 UTC, blueorangutan commented
<b>Trillian test result (tid-3057)</b>
Environment: xenserver-71 (x2), Advanced Networking with Mgmt server 7
Total time taken: 32604 seconds
Marvin logs: https://github.com/blueorangutan/acs-prs/releases/download/trillian/pr4307-t3057-xenserver-71.zip
Intermittent failure detected: /marvin/tests/smoke/test_iso.py
Intermittent failure detected: /marvin/tests/smoke/test_scale_vm.py
Intermittent failure detected: /marvin/tests/smoke/test_snapshots.py
Intermittent failure detected: /marvin/tests/smoke/test_storage_policy.py
Intermittent failure detected: /marvin/tests/smoke/test_usage.py
Smoke tests completed. 81 look OK, 5 have error(s)
Only failed tests results shown below:


Test | Result | Time (s) | Test File
--- | --- | --- | ---
test_04_extract_Iso | `Failure` | 128.42 | test_iso.py
test_01_scale_vm | `Failure` | 9.35 | test_scale_vm.py
test_02_list_snapshots_with_removed_data_store | `Error` | 12.30 | test_snapshots.py
ContextSuite context=TestVMWareStoragePolicies>:teardown | `Error` | 1.56 | test_storage_policy.py
test_01_volume_usage | `Error` | 7.36 | test_usage.py

2020-10-23 06:51 UTC, andrijapanicsb commented
@blueorangutan test centos7 xenserver-71

2020-10-23 06:52 UTC, blueorangutan commented
@andrijapanicsb a Trillian-Jenkins test job (centos7 mgmt + xenserver-71) has been kicked to run smoke tests

2020-10-23 08:48 UTC, blueorangutan commented
<b>Trillian test result (tid-3060)</b>
Environment: vmware-67u3 (x2), Advanced Networking with Mgmt server 7
Total time taken: 41208 seconds
Marvin logs: https://github.com/blueorangutan/acs-prs/releases/download/trillian/pr4307-t3060-vmware-67u3.zip
Intermittent failure detected: /marvin/tests/smoke/test_kubernetes_clusters.py
Intermittent failure detected: /marvin/tests/smoke/test_storage_policy.py
Intermittent failure detected: /marvin/tests/smoke/test_templates.py
Intermittent failure detected: /marvin/tests/smoke/test_volumes.py
Smoke tests completed. 82 look OK, 4 have error(s)
Only failed tests results shown below:


Test | Result | Time (s) | Test File
--- | --- | --- | ---
test_03_deploy_and_upgrade_kubernetes_cluster | `Failure` | 769.66 | test_kubernetes_clusters.py
test_01_import_storage_policies | `Error` | 3.44 | test_storage_policy.py
ContextSuite context=TestVMWareStoragePolicies>:teardown | `Error` | 4.57 | test_storage_policy.py
test_02_create_template_with_checksum_sha1 | `Error` | 5.20 | test_templates.py
test_03_create_template_with_checksum_sha256 | `Error` | 5.22 | test_templates.py
test_04_create_template_with_checksum_md5 | `Error` | 5.18 | test_templates.py
test_10_list_volumes | `Failure` | 369.56 | test_volumes.py

2020-10-23 09:00 UTC, borisstoyanov approved these changes
LGTM

2020-10-23 09:10 UTC, borisstoyanov commented
We often see these failures, let me restart@blueorangutan test centos7 vmware-67u3

2020-10-23 09:11 UTC, blueorangutan commented
@borisstoyanov a Trillian-Jenkins test job (centos7 mgmt + vmware-67u3) has been kicked to run smoke tests

2020-10-23 13:40 UTC, nvazquez commented
@blueorangutan package

2020-10-23 13:41 UTC, blueorangutan commented
@nvazquez a Jenkins job has been kicked to build packages. I'll keep you posted as I make progress.

2020-10-23 14:13 UTC, blueorangutan commented
Packaging result: ✔centos7 ✔centos8 ✔debian. JID-2270

2020-10-23 14:23 UTC, nvazquez commented
@blueorangutan test centos7 vmware-67u3

2020-10-23 14:24 UTC, blueorangutan commented
@nvazquez a Trillian-Jenkins test job (centos7 mgmt + vmware-67u3) has been kicked to run smoke tests

2020-10-23 17:48 UTC, blueorangutan commented
<b>Trillian test result (tid-3063)</b>
Environment: xenserver-71 (x2), Advanced Networking with Mgmt server 7
Total time taken: 37684 seconds
Marvin logs: https://github.com/blueorangutan/acs-prs/releases/download/trillian/pr4307-t3063-xenserver-71.zip
Intermittent failure detected: /marvin/tests/smoke/test_outofbandmanagement.py
Intermittent failure detected: /marvin/tests/smoke/test_scale_vm.py
Intermittent failure detected: /marvin/tests/smoke/test_snapshots.py
Intermittent failure detected: /marvin/tests/smoke/test_usage.py
Intermittent failure detected: /marvin/tests/smoke/test_vpc_redundant.py
Smoke tests completed. 82 look OK, 4 have error(s)
Only failed tests results shown below:


Test | Result | Time (s) | Test File
--- | --- | --- | ---
test_01_scale_vm | `Failure` | 10.33 | test_scale_vm.py
test_02_list_snapshots_with_removed_data_store | `Error` | 11.25 | test_snapshots.py
test_01_volume_usage | `Error` | 7.36 | test_usage.py
test_01_create_redundant_VPC_2tiers_4VMs_4IPs_4PF_ACL | `Failure` | 861.33 | test_vpc_redundant.py
test_02_redundant_VPC_default_routes | `Failure` | 442.36 | test_vpc_redundant.py

2020-10-23 21:08 UTC, blueorangutan commented
<b>Trillian test result (tid-3064)</b>
Environment: vmware-67u3 (x2), Advanced Networking with Mgmt server 7
Total time taken: 41239 seconds
Marvin logs: https://github.com/blueorangutan/acs-prs/releases/download/trillian/pr4307-t3064-vmware-67u3.zip
Intermittent failure detected: /marvin/tests/smoke/test_kubernetes_clusters.py
Intermittent failure detected: /marvin/tests/smoke/test_storage_policy.py
Intermittent failure detected: /marvin/tests/smoke/test_templates.py
Intermittent failure detected: /marvin/tests/smoke/test_vpc_vpn.py
Smoke tests completed. 83 look OK, 3 have error(s)
Only failed tests results shown below:


Test | Result | Time (s) | Test File
--- | --- | --- | ---
test_03_deploy_and_upgrade_kubernetes_cluster | `Failure` | 793.48 | test_kubernetes_clusters.py
test_01_import_storage_policies | `Error` | 3.49 | test_storage_policy.py
ContextSuite context=TestVMWareStoragePolicies>:teardown | `Error` | 4.64 | test_storage_policy.py
test_02_create_template_with_checksum_sha1 | `Error` | 5.20 | test_templates.py
test_03_create_template_with_checksum_sha256 | `Error` | 5.21 | test_templates.py
test_04_create_template_with_checksum_md5 | `Error` | 5.21 | test_templates.py

2020-10-24 12:36 UTC, blueorangutan commented
<b>Trillian test result (tid-3066)</b>
Environment: vmware-67u3 (x2), Advanced Networking with Mgmt server 7
Total time taken: 78093 seconds
Marvin logs: https://github.com/blueorangutan/acs-prs/releases/download/trillian/pr4307-t3066-vmware-67u3.zip
Intermittent failure detected: /marvin/tests/smoke/test_kubernetes_clusters.py
Intermittent failure detected: /marvin/tests/smoke/test_storage_policy.py
Intermittent failure detected: /marvin/tests/smoke/test_templates.py
Smoke tests completed. 82 look OK, 3 have error(s)
Only failed tests results shown below:


Test | Result | Time (s) | Test File
--- | --- | --- | ---
test_03_deploy_and_upgrade_kubernetes_cluster | `Failure` | 787.74 | test_kubernetes_clusters.py
test_01_import_storage_policies | `Error` | 3.48 | test_storage_policy.py
ContextSuite context=TestVMWareStoragePolicies>:teardown | `Error` | 4.62 | test_storage_policy.py
test_02_create_template_with_checksum_sha1 | `Error` | 5.20 | test_templates.py
test_03_create_template_with_checksum_sha256 | `Error` | 5.19 | test_templates.py
test_04_create_template_with_checksum_md5 | `Error` | 5.19 | test_templates.py

2020-10-24 15:15 UTC, borisstoyanov commented
I think test_templates we can ignore, not sure what's wrong with kubernetes_cluster. 
test_storage_policy is introduced in this PR and it looks like the test needs fixing.

2020-10-24 16:03 UTC, nvazquez commented
@blueorangutan package

2020-10-24 16:04 UTC, blueorangutan commented
@nvazquez a Jenkins job has been kicked to build packages. I'll keep you posted as I make progress.

2020-10-24 16:36 UTC, blueorangutan commented
Packaging result: ✔centos7 ✔centos8 ✔debian. JID-2271

2020-10-24 16:39 UTC, nvazquez commented
@blueorangutan test centos7 vmware-67u3

2020-10-24 16:40 UTC, blueorangutan commented
@nvazquez a Trillian-Jenkins test job (centos7 mgmt + vmware-67u3) has been kicked to run smoke tests

2020-10-24 16:47 UTC, DaanHoogland commented
> I think test_templates we can ignore, not sure what's wrong with kubernetes_cluster.
> test_storage_policy is introduced in this PR and it looks like the test needs fixing.

the second of the failures is in the cleanup, a network offerning being deleted while a network is still using it. should be easy to fix.
I'll look at the other later

2020-10-25 05:20 UTC, nvazquez commented
@blueorangutan package

2020-10-25 05:21 UTC, blueorangutan commented
@nvazquez a Jenkins job has been kicked to build packages. I'll keep you posted as I make progress.

2020-10-25 05:48 UTC, blueorangutan commented
Packaging result: ✖centos7 ✖centos8 ✖debian. JID-2272

2020-10-25 05:49 UTC, nvazquez commented
@blueorangutan package

2020-10-25 05:50 UTC, blueorangutan commented
@nvazquez a Jenkins job has been kicked to build packages. I'll keep you posted as I make progress.

2020-10-25 05:54 UTC, nvazquez commented
@blueorangutan package

2020-10-25 05:55 UTC, blueorangutan commented
@nvazquez a Jenkins job has been kicked to build packages. I'll keep you posted as I make progress.

2020-10-25 06:24 UTC, blueorangutan commented
<b>Trillian test result (tid-3067)</b>
Environment: vmware-67u3 (x2), Advanced Networking with Mgmt server 7
Total time taken: 47924 seconds
Marvin logs: https://github.com/blueorangutan/acs-prs/releases/download/trillian/pr4307-t3067-vmware-67u3.zip
Intermittent failure detected: /marvin/tests/smoke/test_kubernetes_clusters.py
Intermittent failure detected: /marvin/tests/smoke/test_storage_policy.py
Intermittent failure detected: /marvin/tests/smoke/test_volumes.py
Smoke tests completed. 83 look OK, 2 have error(s)
Only failed tests results shown below:


Test | Result | Time (s) | Test File
--- | --- | --- | ---
test_03_deploy_and_upgrade_kubernetes_cluster | `Failure` | 809.16 | test_kubernetes_clusters.py
test_01_import_storage_policies | `Error` | 2.90 | test_storage_policy.py
ContextSuite context=TestVMWareStoragePolicies>:teardown | `Error` | 3.96 | test_storage_policy.py

2020-10-25 06:27 UTC, blueorangutan commented
Packaging result: ✔centos7 ✔centos8 ✔debian. JID-2274

2020-10-25 06:28 UTC, nvazquez commented
@blueorangutan test matrix

2020-10-25 06:29 UTC, blueorangutan commented
@nvazquez a Trillian-Jenkins matrix job (centos7 mgmt + xs71, centos7 mgmt + vmware65, centos7 mgmt + kvmcentos7) has been kicked to run smoke tests

2020-10-25 06:30 UTC, nvazquez commented
@blueorangutan test centos7 vmware-67u3

2020-10-25 06:31 UTC, blueorangutan commented
@nvazquez a Trillian-Jenkins test job (centos7 mgmt + vmware-67u3) has been kicked to run smoke tests

2020-10-25 15:33 UTC, blueorangutan commented
<b>Trillian test result (tid-3069)</b>
Environment: kvm-centos7 (x2), Advanced Networking with Mgmt server 7
Total time taken: 30614 seconds
Marvin logs: https://github.com/blueorangutan/acs-prs/releases/download/trillian/pr4307-t3069-kvm-centos7.zip
Smoke tests completed. 86 look OK, 0 have error(s)
Only failed tests results shown below:


Test | Result | Time (s) | Test File
--- | --- | --- | ---

2020-10-25 16:15 UTC, blueorangutan commented
<b>Trillian test result (tid-3068)</b>
Environment: xenserver-71 (x2), Advanced Networking with Mgmt server 7
Total time taken: 33437 seconds
Marvin logs: https://github.com/blueorangutan/acs-prs/releases/download/trillian/pr4307-t3068-xenserver-71.zip
Intermittent failure detected: /marvin/tests/smoke/test_privategw_acl.py
Intermittent failure detected: /marvin/tests/smoke/test_scale_vm.py
Intermittent failure detected: /marvin/tests/smoke/test_usage.py
Smoke tests completed. 85 look OK, 1 have error(s)
Only failed tests results shown below:


Test | Result | Time (s) | Test File
--- | --- | --- | ---
test_01_scale_vm | `Failure` | 9.34 | test_scale_vm.py

2020-10-25 17:30 UTC, blueorangutan commented
<b>Trillian test result (tid-3071)</b>
Environment: vmware-67u3 (x2), Advanced Networking with Mgmt server 7
Total time taken: 37791 seconds
Marvin logs: https://github.com/blueorangutan/acs-prs/releases/download/trillian/pr4307-t3071-vmware-67u3.zip
Intermittent failure detected: /marvin/tests/smoke/test_kubernetes_clusters.py
Intermittent failure detected: /marvin/tests/smoke/test_storage_policy.py
Smoke tests completed. 84 look OK, 2 have error(s)
Only failed tests results shown below:


Test | Result | Time (s) | Test File
--- | --- | --- | ---
test_03_deploy_and_upgrade_kubernetes_cluster | `Failure` | 774.30 | test_kubernetes_clusters.py
test_01_import_storage_policies | `Error` | 2.02 | test_storage_policy.py

2020-10-25 17:43 UTC, blueorangutan commented
<b>Trillian test result (tid-3070)</b>
Environment: vmware-65u2 (x2), Advanced Networking with Mgmt server 7
Total time taken: 38687 seconds
Marvin logs: https://github.com/blueorangutan/acs-prs/releases/download/trillian/pr4307-t3070-vmware-65u2.zip
Intermittent failure detected: /marvin/tests/smoke/test_kubernetes_clusters.py
Intermittent failure detected: /marvin/tests/smoke/test_storage_policy.py
Smoke tests completed. 84 look OK, 2 have error(s)
Only failed tests results shown below:


Test | Result | Time (s) | Test File
--- | --- | --- | ---
test_03_deploy_and_upgrade_kubernetes_cluster | `Failure` | 1455.72 | test_kubernetes_clusters.py
test_01_import_storage_policies | `Error` | 2.32 | test_storage_policy.py

2020-10-25 18:14 UTC, nvazquez commented
@blueorangutan package

2020-10-25 18:15 UTC, blueorangutan commented
@nvazquez a Jenkins job has been kicked to build packages. I'll keep you posted as I make progress.

2020-10-25 18:48 UTC, blueorangutan commented
Packaging result: ✔centos7 ✔centos8 ✔debian. JID-2275

2020-10-25 18:55 UTC, borisstoyanov commented
@blueorangutan test centos7 vmware-67u3

2020-10-25 18:56 UTC, blueorangutan commented
@borisstoyanov a Trillian-Jenkins test job (centos7 mgmt + vmware-67u3) has been kicked to run smoke tests

2020-10-26 09:02 UTC, blueorangutan commented
<b>Trillian test result (tid-3072)</b>
Environment: vmware-67u3 (x2), Advanced Networking with Mgmt server 7
Total time taken: 49205 seconds
Marvin logs: https://github.com/blueorangutan/acs-prs/releases/download/trillian/pr4307-t3072-vmware-67u3.zip
Intermittent failure detected: /marvin/tests/smoke/test_kubernetes_clusters.py
Intermittent failure detected: /marvin/tests/smoke/test_storage_policy.py
Intermittent failure detected: /marvin/tests/smoke/test_volumes.py
Smoke tests completed. 84 look OK, 2 have error(s)
Only failed tests results shown below:


Test | Result | Time (s) | Test File
--- | --- | --- | ---
test_03_deploy_and_upgrade_kubernetes_cluster | `Failure` | 838.00 | test_kubernetes_clusters.py
test_08_deploy_and_upgrade_kubernetes_ha_cluster | `Failure` | 625.66 | test_kubernetes_clusters.py
test_01_import_storage_policies | `Error` | 52.90 | test_storage_policy.py

2020-10-26 12:08 UTC, nvazquez commented
@blueorangutan package

2020-10-26 12:09 UTC, blueorangutan commented
@nvazquez a Jenkins job has been kicked to build packages. I'll keep you posted as I make progress.

2020-10-26 12:30 UTC, borisstoyanov commented
Kubernetes cluster test seems to be present in other PRs as well, I've run this on the test env we have with this PR and got 
```
=== TestName: test_01_deploy_kubernetes_cluster | Status : SUCCESS ===

=== TestName: test_02_invalid_upgrade_kubernetes_cluster | Status : SUCCESS ===

=== TestName: test_03_deploy_and_upgrade_kubernetes_cluster | Status : FAILED ===

=== TestName: test_04_deploy_and_scale_kubernetes_cluster | Status : SUCCESS ===

=== TestName: test_05_delete_kubernetes_cluster | Status : SUCCESS ===

=== TestName: test_06_deploy_invalid_kubernetes_ha_cluster | Status : SUCCESS ===

=== TestName: test_07_deploy_kubernetes_ha_cluster | Status : SUCCESS ===

=== TestName: test_08_deploy_and_upgrade_kubernetes_ha_cluster | Status : SUCCESS ===

=== TestName: test_09_delete_kubernetes_ha_cluster | Status : SUCCESS ===
```

Then the same error with test03 has been seen here as well: 
https://github.com/apache/cloudstack/pull/4382#issuecomment-706347417

The storage policy failure is related to setup and using an incompatible policy with our infra, we'll fix the test now to evade this action and we'll look to fix this one later as it's not breaking anything. 


I think we're in a good position to merge this!

2020-10-26 12:42 UTC, blueorangutan commented
Packaging result: ✔centos7 ✔centos8 ✔debian. JID-2277

2020-10-26 12:45 UTC, nvazquez commented
@blueorangutan package

2020-10-26 12:46 UTC, blueorangutan commented
@nvazquez a Jenkins job has been kicked to build packages. I'll keep you posted as I make progress.

2020-10-26 13:04 UTC, borisstoyanov commented
cat /marvin//MarvinLogs/test_storage_policy_DFIU0C/results.txt
Test VMWare storage policies ... === TestName: test_01_import_storage_policies | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 1 test in 70.694s

OK
LGTM, locally tested

2020-10-26 13:18 UTC, blueorangutan commented
Packaging result: ✔centos7 ✔centos8 ✔debian. JID-2278

2020-10-26 13:21 UTC, nvazquez commented
@blueorangutan test matrix

2020-10-26 13:22 UTC, blueorangutan commented
@nvazquez a Trillian-Jenkins matrix job (centos7 mgmt + xs71, centos7 mgmt + vmware65, centos7 mgmt + kvmcentos7) has been kicked to run smoke tests

2020-10-26 13:22 UTC, nvazquez commented
@blueorangutan test centos7 vmware-67u3

2020-10-26 13:23 UTC, blueorangutan commented
@nvazquez a Trillian-Jenkins test job (centos7 mgmt + vmware-67u3) has been kicked to run smoke tests

2020-10-26 13:24 UTC, merged

2020-10-26 16:04 UTC, weizhouapache commented
@borisstoyanov @nvazquez 
I think we normally merge a pr with only 1 commit.

2020-10-26 18:00 UTC, borisstoyanov commented
Sorry what's the best way to do it? Revert will create yet another pull request..

2020-10-26 23:16 UTC, blueorangutan commented
<b>Trillian test result (tid-3077)</b>
Environment: kvm-centos7 (x2), Advanced Networking with Mgmt server 7
Total time taken: 33433 seconds
Marvin logs: https://github.com/blueorangutan/acs-prs/releases/download/trillian/pr4307-t3077-kvm-centos7.zip
Intermittent failure detected: /marvin/tests/smoke/test_kubernetes_clusters.py
Smoke tests completed. 85 look OK, 1 have error(s)
Only failed tests results shown below:


Test | Result | Time (s) | Test File
--- | --- | --- | ---
test_03_deploy_and_upgrade_kubernetes_cluster | `Failure` | 248.51 | test_kubernetes_clusters.py

2020-10-27 00:26 UTC, blueorangutan commented
<b>Trillian test result (tid-3079)</b>
Environment: vmware-67u3 (x2), Advanced Networking with Mgmt server 7
Total time taken: 37821 seconds
Marvin logs: https://github.com/blueorangutan/acs-prs/releases/download/trillian/pr4307-t3079-vmware-67u3.zip
Intermittent failure detected: /marvin/tests/smoke/test_kubernetes_clusters.py
Smoke tests completed. 85 look OK, 1 have error(s)
Only failed tests results shown below:


Test | Result | Time (s) | Test File
--- | --- | --- | ---
test_03_deploy_and_upgrade_kubernetes_cluster | `Failure` | 791.03 | test_kubernetes_clusters.py

2020-10-27 00:31 UTC, blueorangutan commented
<b>Trillian test result (tid-3078)</b>
Environment: vmware-65u2 (x2), Advanced Networking with Mgmt server 7
Total time taken: 38296 seconds
Marvin logs: https://github.com/blueorangutan/acs-prs/releases/download/trillian/pr4307-t3078-vmware-65u2.zip
Intermittent failure detected: /marvin/tests/smoke/test_kubernetes_clusters.py
Smoke tests completed. 85 look OK, 1 have error(s)
Only failed tests results shown below:


Test | Result | Time (s) | Test File
--- | --- | --- | ---
test_03_deploy_and_upgrade_kubernetes_cluster | `Failure` | 782.42 | test_kubernetes_clusters.py

2020-10-27 11:56 UTC, blueorangutan commented
<b>Trillian test result (tid-3076)</b>
Environment: xenserver-71 (x2), Advanced Networking with Mgmt server 7
Total time taken: 79402 seconds
Marvin logs: https://github.com/blueorangutan/acs-prs/releases/download/trillian/pr4307-t3076-xenserver-71.zip
Intermittent failure detected: /marvin/tests/smoke/test_public_ip_range.py
Intermittent failure detected: /marvin/tests/smoke/test_reset_vm_on_reboot.py
Intermittent failure detected: /marvin/tests/smoke/test_resource_accounting.py
Intermittent failure detected: /marvin/tests/smoke/test_router_dhcphosts.py
Intermittent failure detected: /marvin/tests/smoke/test_router_dns.py
Intermittent failure detected: /marvin/tests/smoke/test_router_dnsservice.py
Intermittent failure detected: /marvin/tests/smoke/test_routers_iptables_default_policy.py
Intermittent failure detected: /marvin/tests/smoke/test_routers_network_ops.py
Intermittent failure detected: /marvin/tests/smoke/test_routers.py
Intermittent failure detected: /marvin/tests/smoke/test_scale_vm.py
Intermittent failure detected: /marvin/tests/smoke/test_service_offerings.py
Intermittent failure detected: /marvin/tests/smoke/test_snapshots.py
Intermittent failure detected: /marvin/tests/smoke/test_ssvm.py
Intermittent failure detected: /marvin/tests/smoke/test_storage_policy.py
Intermittent failure detected: /marvin/tests/smoke/test_templates.py
Intermittent failure detected: /marvin/tests/smoke/test_usage.py
Intermittent failure detected: /marvin/tests/smoke/test_vm_life_cycle.py
Intermittent failure detected: /marvin/tests/smoke/test_vm_snapshots.py
Intermittent failure detected: /marvin/tests/smoke/test_volumes.py
Intermittent failure detected: /marvin/tests/smoke/test_vpc_redundant.py
Intermittent failure detected: /marvin/tests/smoke/test_vpc_router_nics.py
Intermittent failure detected: /marvin/tests/smoke/test_vpc_vpn.py
Intermittent failure detected: /marvin/tests/smoke/test_host_maintenance.py
Smoke tests completed. 64 look OK, 22 have error(s)
Only failed tests results shown below:


Test | Result | Time (s) | Test File
--- | --- | --- | ---
ContextSuite context=TestResetVmOnReboot>:setup | `Error` | 0.00 | test_reset_vm_on_reboot.py
ContextSuite context=TestRouterDHCPHosts>:setup | `Error` | 0.00 | test_router_dhcphosts.py
ContextSuite context=TestRouterDHCPOpts>:setup | `Error` | 0.00 | test_router_dhcphosts.py
ContextSuite context=TestRAMCPUResourceAccounting>:setup | `Error` | 0.00 | test_resource_accounting.py
ContextSuite context=TestRouterDns>:setup | `Error` | 0.00 | test_router_dns.py
ContextSuite context=TestRouterDnsService>:setup | `Error` | 0.00 | test_router_dnsservice.py
ContextSuite context=TestRouterIpTablesPolicies>:setup | `Error` | 0.00 | test_routers_iptables_default_policy.py
ContextSuite context=TestVPCIpTablesPolicies>:setup | `Error` | 0.00 | test_routers_iptables_default_policy.py
ContextSuite context=TestIsolatedNetworks>:setup | `Error` | 0.00 | test_routers_network_ops.py
ContextSuite context=TestRedundantIsolateNetworks>:setup | `Error` | 0.00 | test_routers_network_ops.py
ContextSuite context=TestRouterServices>:setup | `Error` | 0.00 | test_routers.py
ContextSuite context=TestScaleVm>:setup | `Error` | 0.00 | test_scale_vm.py
ContextSuite context=TestServiceOfferings>:setup | `Error` | 1513.62 | test_service_offerings.py
ContextSuite context=TestSnapshotRootDisk>:setup | `Error` | 0.00 | test_snapshots.py
test_01_list_sec_storage_vm | `Failure` | 0.04 | test_ssvm.py
test_02_list_cpvm_vm | `Failure` | 0.04 | test_ssvm.py
test_03_ssvm_internals | `Failure` | 0.04 | test_ssvm.py
test_04_cpvm_internals | `Failure` | 0.04 | test_ssvm.py
test_05_stop_ssvm | `Failure` | 0.04 | test_ssvm.py
test_06_stop_cpvm | `Failure` | 0.04 | test_ssvm.py
test_07_reboot_ssvm | `Failure` | 0.04 | test_ssvm.py
test_08_reboot_cpvm | `Failure` | 0.04 | test_ssvm.py
test_09_destroy_ssvm | `Failure` | 0.05 | test_ssvm.py
test_10_destroy_cpvm | `Failure` | 0.04 | test_ssvm.py
ContextSuite context=TestVMWareStoragePolicies>:setup | `Error` | 0.00 | test_storage_policy.py
test_02_create_template_with_checksum_sha1 | `Error` | 65.49 | test_templates.py
test_03_create_template_with_checksum_sha256 | `Error` | 65.51 | test_templates.py
test_04_create_template_with_checksum_md5 | `Error` | 65.52 | test_templates.py
test_05_create_template_with_no_checksum | `Error` | 65.49 | test_templates.py
ContextSuite context=TestTemplates>:setup | `Error` | 2.35 | test_templates.py
ContextSuite context=TestISOUsage>:setup | `Error` | 0.00 | test_usage.py
ContextSuite context=TestLBRuleUsage>:setup | `Error` | 0.00 | test_usage.py
ContextSuite context=TestNatRuleUsage>:setup | `Error` | 0.00 | test_usage.py
ContextSuite context=TestPublicIPUsage>:setup | `Error` | 0.00 | test_usage.py
ContextSuite context=TestSnapshotUsage>:setup | `Error` | 0.00 | test_usage.py
ContextSuite context=TestVmUsage>:setup | `Error` | 0.00 | test_usage.py
ContextSuite context=TestVolumeUsage>:setup | `Error` | 0.00 | test_usage.py
ContextSuite context=TestVpnUsage>:setup | `Error` | 0.00 | test_usage.py
ContextSuite context=Test01DeployVM>:setup | `Error` | 0.00 | test_vm_life_cycle.py
ContextSuite context=Test02VMLifeCycle>:setup | `Error` | 0.00 | test_vm_life_cycle.py
ContextSuite context=TestChangeServiceOfferingForVmWithSnapshots>:setup | `Error` | 0.00 | test_vm_snapshots.py
ContextSuite context=TestVmSnapshot>:setup | `Error` | 0.00 | test_vm_snapshots.py
ContextSuite context=TestCreateVolume>:setup | `Error` | 0.00 | test_volumes.py
ContextSuite context=TestVolumes>:setup | `Error` | 0.00 | test_volumes.py
ContextSuite context=TestVPCRedundancy>:setup | `Error` | 0.00 | test_vpc_redundant.py
ContextSuite context=TestVPCNics>:setup | `Error` | 0.00 | test_vpc_router_nics.py
ContextSuite context=TestRVPCSite2SiteVpn>:setup | `Error` | 0.00 | test_vpc_vpn.py
ContextSuite context=TestVPCSite2SiteVPNMultipleOptions>:setup | `Error` | 0.00 | test_vpc_vpn.py
ContextSuite context=TestVpcRemoteAccessVpn>:setup | `Error` | 0.00 | test_vpc_vpn.py
ContextSuite context=TestVpcSite2SiteVpn>:setup | `Error` | 0.00 | test_vpc_vpn.py
test_02_cancel_host_maintenace_with_migration_jobs | `Error` | 1513.72 | test_host_maintenance.py

2020-11-24 05:19 UTC, sureshanaparti commented on server/src/main/java/com/cloud/vm/UserVmManagerImpl.java
> +        }
these changes are reverted in the PR https://github.com/apache/cloudstack/pull/4493 , as the data disks (which are not to be deleted) are being detached on destroy VM, which is breaking the existing behavior.