Allow users to update volume name
apache/cloudstack pull request #4584
Opened 2021-01-14 09:26 UTC by ravening

### Description

Provide an api support to update volume name by all users
Can be done both through api and UI

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

### Feature/Enhancement Scale or Bug Severity

#### Feature/Enhancement Scale

- [ ] Major
- [X] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [X] Trivial

### Screenshots (if appropriate):

![Screenshot 2021-01-14 at 10 25 29](https://user-images.githubusercontent.com/10645273/104570972-d5d8e300-5652-11eb-830d-e0d5603964b3.png)

### How Has This Been Tested?

Through API

```
update volume id=3e8f9553-e1c9-4ac0-bb43-10d7d928daf2 name=test-admin
```

2021-01-15 15:01 UTC, RodrigoDLopez requested changes
I am trying to understand in which scenario it is necessary to give freedom for ordinary users to change names within the environment.
You can explain it to me because I couldn't reach a conclusion on my own.

2021-01-18 15:28 UTC, DaanHoogland approved these changes

2021-01-19 12:23 UTC, ravening commented
> I am trying to understand in which scenario it is necessary to give freedom for ordinary users to change names within the environment.
> You can explain it to me because I couldn't reach a conclusion on my own.

@RodrigoDLopez there is no harm in changing the volume name. so anybody can do it

2021-01-19 12:25 UTC, ravening commented on api/src/main/java/org/apache/cloudstack/api/command/user/volume/UpdateVolumeCmd.java
> +    @Parameter(name = ApiConstants.NAME, type = CommandType.STRING, description = "new name of the volume", since = "4.16")
Other parameters have sensitive info whereas the "name" parameter is not critical.
So regular users can change only name but not other important values

2021-01-19 12:25 UTC, ravening commented on api/src/main/java/org/apache/cloudstack/api/command/user/volume/UpdateVolumeCmd.java
> +            since = "4.4", authorized = {RoleType.Admin})
admins and regular users can run this command. but regular users can only change name

2021-01-19 13:10 UTC, RodrigoDLopez approved these changes
@ravening I know that changing volume names does no harm, but I don't like empowering users even if they are cosmetic powers.
But you have my approval and my +1

2021-01-19 13:36 UTC, weizhouapache approved these changes

2021-01-19 13:37 UTC, weizhouapache commented
code lgtm

2021-01-26 11:18 UTC, closed without merging

2021-01-26 12:26 UTC, mib1185 commented
Hi @ravening 
why did you close this PR before merge? 🤔

2021-01-26 13:06 UTC, ravening commented
> Hi @ravening
> why did you close this PR before merge? 🤔

@mib1185 sorry it got closed after some rebase with my branch.. I have opened new pr with ui changes in https://github.com/apache/cloudstack/pull/4618