ui: Allow IP range creation for Physical Network - Guest Traffic
apache/cloudstack pull request #5020
Opened 2021-05-12 10:08 UTC by Pearl1594

### Description

For Basic Zones, additional IP ranges can be added for the guest traffic, however, in the new UI, it isn't possible to add IP ranges.
Legacy UI:
![image](https://user-images.githubusercontent.com/10495417/117957001-3a712980-b337-11eb-9a7a-7f91254e7dd6.png)

Current UI:
Doesn't have the provision for adding additional IP range.
![image](https://user-images.githubusercontent.com/10495417/117957223-7906e400-b337-11eb-8c68-dc2533f7c2b6.png)

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

### Feature/Enhancement Scale or Bug Severity
#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [X] Major
- [ ] Minor
- [ ] Trivial

### Screenshots (if appropriate):

### How Has This Been Tested?
![image](https://user-images.githubusercontent.com/10495417/117957769-02b6b180-b338-11eb-9023-e972fa7ccf23.png)

2021-05-12 10:09 UTC, Pearl1594 commented
@blueorangutan ui

2021-05-12 10:10 UTC, blueorangutan commented
@Pearl1594 a Jenkins job has been kicked to build UI QA env. I'll keep you posted as I make progress.

2021-05-12 10:14 UTC, blueorangutan commented
UI build: :heavy_check_mark:
Live QA URL: http://qa.cloudstack.cloud:8080/client/pr/5020 (SL-JID-135)

2021-05-12 11:08 UTC, shwstppr requested changes

2021-05-12 11:08 UTC, shwstppr commented on ui/src/views/infra/network/TrafficTypesTab.vue
> +      if (this.networkType === 'Basic') {
@Pearl1594 Can you please check if this even called. Default value for `networkType` is `Advanced` and `fetchGuestNetwork` is called before finding `networkType` at line 147. I think `network` object of IpRangesTabPublic.vue will always remain empty.

2021-05-12 11:54 UTC, rhtyd commented
Is it available if you go to the network -> ip ranges? I think I saw some change by someone recently for shared networks (adding IP range).

2021-05-12 11:58 UTC, Pearl1594 commented
@blueorangutan ui

2021-05-12 11:59 UTC, blueorangutan commented
@Pearl1594 a Jenkins job has been kicked to build UI QA env. I'll keep you posted as I make progress.

2021-05-12 12:01 UTC, Pearl1594 commented
@rhtyd I don't see that option 
![image](https://user-images.githubusercontent.com/10495417/117971622-c4c18980-b347-11eb-9d53-7a897f460770.png)

2021-05-12 12:05 UTC, shwstppr commented
@Pearl1594 it is there in 4.15 branch I think
![Screenshot from 2021-05-12 17-34-02](https://user-images.githubusercontent.com/153340/117972123-5af5af80-b348-11eb-9440-d7e728404245.png)

Though I'm fine we want to provide it in Infra section as well.
cc @rhtyd

2021-05-12 12:05 UTC, blueorangutan commented
UI build: :heavy_check_mark:
Live QA URL: http://qa.cloudstack.cloud:8080/client/pr/5020 (SL-JID-136)

2021-05-13 02:32 UTC, utchoang approved these changes
LGTM!
A few things in the network area, such as the @rhtyd comment, need to be tweaked.
cc @shwstppr

2021-05-13 09:58 UTC, shwstppr approved these changes
LGTM. Tested, it works fine.
Will be good to have for the consistency in the UI as compared to legacy UI. People accustomed to legacy UI might still use this workflow.

2021-05-14 17:44 UTC, merged