Update chain info of the volumes after migrate operations
apache/cloudstack pull request #5097
Opened 2021-06-10 09:44 UTC by harikrishna-patnala

### Description
This PR fixes the problem of not updating the chain info or setting chain info to null after volume migrations.

Problem: While fetching the volume chain info, management server assumes datastore name to be a UUID (this is true only for NFS storages added by CloudStack) but datastore name can be with any name.
Solution: To fetch the volume chain info, use datastore name instead of UUID.

The fix is made in the flow of following API operations
1. migrateVirtualMachine
2. migrateVirtualMachineWithVolume
3. migrateVolume 

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

### Feature/Enhancement Scale or Bug Severity

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### Screenshots (if appropriate):

### How Has This Been Tested?

Created one NFS, one datastore cluster (with two child storages with names "child1", "child2") primary storages
1. Migrated a volume from NFS to datastore cluster. 'chain_info' in "volumes" table is updated
Before migration
![image](https://user-images.githubusercontent.com/3348673/121502618-f6d51280-c9fd-11eb-93ab-aabfb95b9b9c.png)
After migration
![image](https://user-images.githubusercontent.com/3348673/121502753-166c3b00-c9fe-11eb-9617-91e79fc136ce.png)
2. Migrated volume from datastore cluster to NFS storage. 'chain_info' in "volumes" table is updated
3. called APIs migrateVirtualMachine and migrateVirtualMachineWithVolumes to migrate volumes from NFS to datastore cluster and datastore cluster to NFS, all succeeded and updated the chain_info accordingly.

2021-06-10 09:46 UTC, harikrishna-patnala commented
@blueorangutan package

2021-06-10 09:47 UTC, blueorangutan commented
@harikrishna-patnala a Jenkins job has been kicked to build packages. I'll keep you posted as I make progress.

2021-06-10 10:11 UTC, blueorangutan commented
Packaging result: :heavy_check_mark: centos7 :heavy_check_mark: centos8 :heavy_check_mark: debian. SL-JID 197

2021-06-10 11:33 UTC, harikrishna-patnala commented
@blueorangutan test centos7 vmware-67u3

2021-06-10 11:34 UTC, blueorangutan commented
@harikrishna-patnala a Trillian-Jenkins test job (centos7 mgmt + vmware-67u3) has been kicked to run smoke tests

2021-06-10 11:44 UTC, rhtyd approved these changes

2021-06-10 11:59 UTC, rhtyd commented
Ping @mib1185 @DK101010 can you review/test this in your fork?

2021-06-10 13:32 UTC, DK101010 commented
> Ping @mib1185 @DK101010 can you review/test this in your fork?

Hi @rhtyd, @harikrishna-patnala  I will test this. Many thanks for your quick support.

2021-06-10 14:29 UTC, shwstppr approved these changes
Code LGTM

2021-06-10 15:35 UTC, nvazquez requested changes
@harikrishna-patnala deploy-as-is worked good but got an error using the default template or selecting non-deploy-as-is templates. Can you check?

Deploy-as-is templates are working good, example:

Deployment on VMFS with name ds1:
{"diskDeviceBusName":"scsi0:0","diskChain":["[ds1] i-2-4-VM/i-2-4-VM.vmdk","[ds1] a742fd17-5859-4c48-9c33-60b44dff2d77/a742fd17-5859-4c48-9c33-60b44dff2d77.vmdk"]}

VMFS->NFS:
{"diskDeviceBusName":"scsi0:0","diskChain":["[710b87913b753eed806d7d52594d1aa4] i-2-4-VM/i-2-4-VM.vmdk"]}

NFS->VMFS:
{"diskDeviceBusName":"scsi0:0","diskChain":["[ds1] i-2-4-VM/i-2-4-VM.vmdk"]}

2021-06-11 02:24 UTC, blueorangutan commented
<b>Trillian test result (tid-906)</b>
Environment: vmware-67u3 (x2), Advanced Networking with Mgmt server 7
Total time taken: 52249 seconds
Marvin logs: https://github.com/blueorangutan/acs-prs/releases/download/trillian/pr5097-t906-vmware-67u3.zip
Intermittent failure detected: /marvin/tests/smoke/test_diagnostics.py
Intermittent failure detected: /marvin/tests/smoke/test_kubernetes_clusters.py
Intermittent failure detected: /marvin/tests/smoke/test_loadbalance.py
Intermittent failure detected: /marvin/tests/smoke/test_privategw_acl.py
Intermittent failure detected: /marvin/tests/smoke/test_vm_snapshots.py
Intermittent failure detected: /marvin/tests/smoke/test_vpc_redundant.py
Intermittent failure detected: /marvin/tests/smoke/test_vpc_router_nics.py
Smoke tests completed. 86 look OK, 1 have error(s)
Only failed tests results shown below:


Test | Result | Time (s) | Test File
--- | --- | --- | ---
test_01_create_redundant_VPC_2tiers_4VMs_4IPs_4PF_ACL | `Failure` | 601.04 | test_vpc_redundant.py
test_03_create_redundant_VPC_1tier_2VMs_2IPs_2PF_ACL_reboot_routers | `Failure` | 627.55 | test_vpc_redundant.py
test_05_rvpc_multi_tiers | `Failure` | 551.77 | test_vpc_redundant.py
test_05_rvpc_multi_tiers | `Error` | 586.83 | test_vpc_redundant.py

2021-06-11 03:16 UTC, nvazquez approved these changes
LGTM - Manually tested. Confirmed the issues mentioned earlier were related to my env configuration

2021-06-11 08:21 UTC, mib1185 commented
> Ping @mib1185 @DK101010 can you review/test this in your fork?

@rhtyd tests were successful - works like a charm now 👍 
@harikrishna-patnala many thanks for the fast support und provided fix 👍

2021-06-11 14:35 UTC, rhtyd commented
Merging this based on review, manual tests and smoketests

2021-06-11 14:36 UTC, merged