Added a log line to HttpUploadServerHandler
apache/cloudstack pull request #5983
Opened 2022-02-10 16:43 UTC by JoaoJandre

### Description

When I was trying to upload volumes using CloudMonkey + cURL, the upload would always timeout and the SSVM would not receive the volume's data, even though it was receiving the HTTP headers. By adding this log line, it was possible to find out that cURL sends, by default, a 'Expect: 100-continue' with the HTTP request, and then wait the SSVM response, which never happens. Therefore, this PR proposes to add this log line in case any problems like that in the future happens, they would be more easily discovered by enabling the TRACE log level in the SSVM.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

### Feature/Enhancement Scale or Bug Severity

#### Feature/Enhancement Scale

- [ ] Major
- [X] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [X] Trivial

### How Has This Been Tested?
Uploaded volumes using CMK + cURL and read the SSVM's log files.

2022-02-10 16:49 UTC, GabrielBrascher approved these changes
Code LGTM.
Simple log added.

2022-02-10 21:41 UTC, RodrigoDLopez requested changes
How about remove this new line '\n'. I think we don't need it here

2022-02-11 16:53 UTC, JoaoJandre commented on services/secondary-storage/server/src/main/java/org/apache/cloudstack/storage/resource/HttpUploadServerHandler.java
> +            logger.trace(String.format("HTTP request: \n %s", msg));
Sure

2022-02-11 18:23 UTC, nvazquez approved these changes
LGTM

2022-02-11 18:24 UTC, nvazquez commented
@blueorangutan package

2022-02-11 18:25 UTC, blueorangutan commented
@nvazquez a Jenkins job has been kicked to build packages. I'll keep you posted as I make progress.

2022-02-11 19:02 UTC, blueorangutan commented
Packaging result: :heavy_check_mark: el7 :heavy_check_mark: el8 :heavy_check_mark: debian :heavy_check_mark: suse15. SL-JID 2581

2022-02-11 19:09 UTC, nvazquez commented
@blueorangutan test

2022-02-11 19:10 UTC, blueorangutan commented
@nvazquez a Trillian-Jenkins test job (centos7 mgmt + kvm-centos7) has been kicked to run smoke tests

2022-02-12 05:20 UTC, blueorangutan commented
<b>Trillian test result (tid-3306)</b>
Environment: kvm-centos7 (x2), Advanced Networking with Mgmt server 7
Total time taken: 35224 seconds
Marvin logs: https://github.com/blueorangutan/acs-prs/releases/download/trillian/pr5983-t3306-kvm-centos7.zip
Smoke tests completed. 87 look OK, 5 have errors
Only failed tests results shown below:


Test | Result | Time (s) | Test File
--- | --- | --- | ---
test_01_add_primary_storage_disabled_host | `Error` | 0.56 | test_primary_storage.py
test_01_primary_storage_nfs | `Error` | 0.10 | test_primary_storage.py
ContextSuite context=TestStorageTags>:setup | `Error` | 0.17 | test_primary_storage.py
test_03_deploy_and_scale_kubernetes_cluster | `Failure` | 31.91 | test_kubernetes_clusters.py
test_07_deploy_kubernetes_ha_cluster | `Failure` | 53.39 | test_kubernetes_clusters.py
test_08_upgrade_kubernetes_ha_cluster | `Failure` | 33.87 | test_kubernetes_clusters.py
test_09_delete_kubernetes_ha_cluster | `Failure` | 35.89 | test_kubernetes_clusters.py
ContextSuite context=TestKubernetesCluster>:teardown | `Error` | 125.18 | test_kubernetes_clusters.py
test_01_secure_vm_migration | `Error` | 150.09 | test_vm_life_cycle.py
test_02_unsecure_vm_migration | `Error` | 270.20 | test_vm_life_cycle.py
test_03_secured_to_nonsecured_vm_migration | `Error` | 142.88 | test_vm_life_cycle.py
test_08_migrate_vm | `Error` | 44.79 | test_vm_life_cycle.py
test_02_list_snapshots_with_removed_data_store | `Error` | 8.41 | test_snapshots.py
test_02_list_snapshots_with_removed_data_store | `Error` | 8.41 | test_snapshots.py
test_hostha_enable_ha_when_host_in_maintenance | `Error` | 303.81 | test_hostha_kvm.py

2022-02-12 11:32 UTC, nvazquez commented
@blueorangutan test

2022-02-12 11:33 UTC, blueorangutan commented
@nvazquez a Trillian-Jenkins test job (centos7 mgmt + kvm-centos7) has been kicked to run smoke tests

2022-02-13 14:03 UTC, nvazquez commented
@blueorangutan package

2022-02-13 14:04 UTC, blueorangutan commented
@nvazquez a Jenkins job has been kicked to build packages. I'll keep you posted as I make progress.

2022-02-13 14:40 UTC, blueorangutan commented
Packaging result: :heavy_check_mark: el7 :heavy_check_mark: el8 :heavy_check_mark: debian :heavy_check_mark: suse15. SL-JID 2592

2022-02-13 14:55 UTC, nvazquez commented
@blueorangutan test

2022-02-13 14:56 UTC, blueorangutan commented
@nvazquez a Trillian-Jenkins test job (centos7 mgmt + kvm-centos7) has been kicked to run smoke tests

2022-02-13 23:54 UTC, blueorangutan commented
<b>Trillian test result (tid-3320)</b>
Environment: kvm-centos7 (x2), Advanced Networking with Mgmt server 7
Total time taken: 31015 seconds
Marvin logs: https://github.com/blueorangutan/acs-prs/releases/download/trillian/pr5983-t3320-kvm-centos7.zip
Smoke tests completed. 91 look OK, 1 have errors
Only failed tests results shown below:


Test | Result | Time (s) | Test File
--- | --- | --- | ---
test_01_nic | `Error` | 135.33 | test_nic.py

2022-02-15 14:31 UTC, nvazquez commented on services/secondary-storage/server/src/main/java/org/apache/cloudstack/storage/resource/HttpUploadServerHandler.java
> +            logger.trace(String.format("HTTP request: %s", msg));
@DaanHoogland would you suggest wrapping it by `logger.isTraceEnabled()?

2022-02-15 14:32 UTC, nvazquez commented
@JoaoJandre there is only one outstanding comment, can you please check?

2022-02-15 14:38 UTC, JoaoJandre commented on services/secondary-storage/server/src/main/java/org/apache/cloudstack/storage/resource/HttpUploadServerHandler.java
> +            logger.trace(String.format("HTTP request: %s", msg));
As mentioned in the PR description, we had a problem while uploading volumes using cURL. However, even after changing the log to TRACE level, it was not possible for operators to see what was going on there. By adding this log, we were able to see which headers were being sent (via cURL and UI), which enabled us to resolve the issue. The log was intended to developers and operators, so they can see what is happening in the SSVM side. They (operators and developers/supporters) can change the log level to `TRACE` and see a little bit more of information regarding the processing in the SSVM. On the other hand, if no LOG is ever generated (the current state of the code), changing the LOG level in Log4J does not help anything, and a developer is required to change the code and patch it in runtime in the SSVM, so one can proceed with the troubleshooting.

2022-02-15 15:12 UTC, DaanHoogland commented on services/secondary-storage/server/src/main/java/org/apache/cloudstack/storage/resource/HttpUploadServerHandler.java
> +            logger.trace(String.format("HTTP request: %s", msg));
ok, makes sense @JoaoJandre . Then I would suggest
```suggestion
            if(logger.isTraceEnabled()) {
                logger.trace(String.format("HTTP request: %s", msg));
            }
```
alternative add a higher level, especially if it is meant for operators as well.

2022-02-15 18:20 UTC, blueorangutan commented
Packaging result: :heavy_check_mark: el7 :heavy_check_mark: el8 :heavy_check_mark: debian :heavy_check_mark: suse15. SL-JID 2625

2022-02-16 07:42 UTC, DaanHoogland approved these changes

2022-02-16 11:43 UTC, merged

2022-02-16 11:43 UTC, sureshanaparti approved these changes