Fix osx build
apache/cloudstack pull request #6056
Opened 2022-03-04 10:45 UTC by rohityadavcloud

Fixes maven build unit tests on osx. (Tested on M1 mac)

2022-03-04 10:58 UTC, rohityadavcloud commented
@blueorangutan package

2022-03-04 10:59 UTC, blueorangutan commented
@rohityadavcloud a Jenkins job has been kicked to build packages. I'll keep you posted as I make progress.

2022-03-04 11:09 UTC, blueorangutan commented
Packaging result: :heavy_multiplication_x: el7 :heavy_multiplication_x: el8 :heavy_multiplication_x: debian :heavy_multiplication_x: suse15. SL-JID 2763

2022-03-04 12:12 UTC, nvazquez commented on plugins/hypervisors/kvm/src/test/java/org/apache/cloudstack/utils/linux/MemStatTest.java
> +        memStat.refresh();
I see this is causing issue on linux packaging (also line 60):

````
[ERROR] getMemInfoParseTest(org.apache.cloudstack.utils.linux.MemStatTest)  Time elapsed: 0.005 s  <<< ERROR!
java.lang.IllegalStateException: Scanner closed
	at org.apache.cloudstack.utils.linux.MemStatTest.getMemInfoParseTest(MemStatTest.java:49)
````

2022-03-04 12:35 UTC, nvazquez requested changes

2022-03-04 12:35 UTC, nvazquez commented on plugins/hypervisors/kvm/src/test/java/org/apache/cloudstack/utils/linux/MemStatTest.java
> +        memStat.refresh();
```suggestion
        if (!System.getProperty("os.name").equals("Linux")) {
            return;
        }
```

2022-03-04 12:35 UTC, nvazquez commented on plugins/hypervisors/kvm/src/test/java/org/apache/cloudstack/utils/linux/MemStatTest.java
> +        memStat.refresh();
```suggestion
        if (!System.getProperty("os.name").equals("Linux")) {
            return;
        }
```

2022-03-04 12:55 UTC, rohityadavcloud commented
Thanks for code suggestions @nvazquez it makes sense to skip on OSX.

@blueorangutan package

2022-03-04 13:18 UTC, nvazquez commented
@blueorangutan package

2022-03-04 13:53 UTC, blueorangutan commented
Packaging result: :heavy_check_mark: el7 :heavy_check_mark: el8 :heavy_check_mark: debian :heavy_check_mark: suse15. SL-JID 2764

2022-03-04 14:07 UTC, nvazquez commented
@blueorangutan test

2022-03-04 14:08 UTC, blueorangutan commented
@nvazquez a Trillian-Jenkins test job (centos7 mgmt + kvm-centos7) has been kicked to run smoke tests

2022-03-04 14:08 UTC, nvazquez approved these changes
LGTM

2022-03-04 23:44 UTC, blueorangutan commented
<b>Trillian test result (tid-3486)</b>
Environment: kvm-centos7 (x2), Advanced Networking with Mgmt server 7
Total time taken: 33225 seconds
Marvin logs: https://github.com/blueorangutan/acs-prs/releases/download/trillian/pr6056-t3486-kvm-centos7.zip
Smoke tests completed. 92 look OK, 0 have errors
Only failed tests results shown below:


Test | Result | Time (s) | Test File
--- | --- | --- | ---

2022-03-07 09:24 UTC, shwstppr approved these changes

2022-03-07 09:25 UTC, merged