Allow editing of host and storage tags of system offerings in the UI
apache/cloudstack pull request #7941
Opened 2023-09-04 19:51 UTC by gpordeus

### Description
CloudStack allows you to change host tags and storage tags of system offerings through the API, but it was missing from the UI. This just added the fields so the UI window is the same as the compute offering's window.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

### Feature/Enhancement Scale or Bug Severity

#### Feature/Enhancement Scale

- [ ] Major
- [X] Minor

### Screenshots (if appropriate):
![image](https://github.com/apache/cloudstack/assets/22242548/219ad68e-353b-4b81-91da-58793d48974c)

### How Has This Been Tested?
I created a system offering without host or storage tags, added them through the edit window and verified they were added. I then created another offering with tags, deleted one of them and changed the other to a different one.

2023-09-05 06:02 UTC, harikrishna-patnala commented
@blueorangutan ui

2023-09-05 06:03 UTC, blueorangutan commented
@harikrishna-patnala a Jenkins job has been kicked to build UI QA env. I'll keep you posted as I make progress.

2023-09-05 06:18 UTC, blueorangutan commented
UI build: :heavy_check_mark:
Live QA URL: https://qa.cloudstack.cloud/simulator/pr/7941 (QA-JID-171)

2023-09-05 20:08 UTC, GutoVeronezi approved these changes
CLGTM

2023-09-06 07:20 UTC, rohityadavcloud approved these changes

2023-09-06 11:07 UTC, harikrishna-patnala requested changes
@gpordeus Can you please add 'storagetags' before 'hosttags' in the details array to view the added or updated storagetag in the UI response like below

-      details: ['name', 'id', 'displaytext', 'systemvmtype', 'provisioningtype', 'storagetype', 'iscustomized', 'limitcpuuse', 'cpunumber', 'cpuspeed', 'memory', 'hosttags', 'tags', 'domain', 'zone', 'created', 'dynamicscalingenabled', 'diskofferingstrictness'],
+      details: ['name', 'id', 'displaytext', 'systemvmtype', 'provisioningtype', 'storagetype', 'iscustomized', 'limitcpuuse', 'cpunumber', 'cpuspeed', 'memory', 'storagetags', 'hosttags', 'tags', 'domain', 'zone', 'created', 'dynamicscalingenabled', 'diskofferingstrictness'],
       actions: [{

![image](https://github.com/apache/cloudstack/assets/3348673/6f5bf85c-998b-41dd-8890-f25966f19948)

2023-09-11 08:41 UTC, merged