Fix intermittent build failures
apache/cloudstack pull request #8312
Opened 2023-12-06 09:23 UTC by vishesh92

### Description

This PR fixes intermittent build failures which happen due to parallel test runs. As of now port 9399 is being used in NetworkerClientTest & VeeamClientTest. This PR updates the port in NetworkerClientTest from 9399 to 9400.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [x] build/CI

### Feature/Enhancement Scale or Bug Severity

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### Screenshots (if appropriate):

### How Has This Been Tested?

#### How did you try to break this feature and the system with this change?

2023-12-06 09:24 UTC, rohityadavcloud approved these changes

2023-12-06 09:25 UTC, rohityadavcloud commented
Could we somehow use random/available ports, there has to be a way to do that @vishesh92 ?

2023-12-06 09:45 UTC, kishankavala commented
Can you create a common util similar to the following to find a free port:

```
try (ServerSocket socket = new ServerSocket(0)) {
            socket.setReuseAddress(true);
            return socket.getLocalPort();
        }
```

2023-12-06 10:06 UTC, weizhouapache commented
> Can you create a common util similar to the following to find a free port:
> 
> ```
> try (ServerSocket socket = new ServerSocket(0)) {
>             socket.setReuseAddress(true);
>             return socket.getLocalPort();
>         }
> ```

+1

btw, can we specify a port range ?

2023-12-06 11:01 UTC, shwstppr commented
@vishesh92 will you be adding suggested changes in this PR or can it be done as a separate PR?

2023-12-06 11:20 UTC, vishesh92 commented
@shwstppr Let me make the change in this PR itself.

2023-12-06 11:29 UTC, vishesh92 commented
@kishankavala @shwstppr @DaanHoogland I have made the changes to randomly select a port.

2023-12-06 12:07 UTC, kishankavala commented on plugins/backup/networker/src/test/java/org/apache/backup/networker/NetworkerClientTest.java
> +    private int getRandomPort() {
LGTM otherwise

2023-12-06 12:09 UTC, vishesh92 commented on plugins/backup/networker/src/test/java/org/apache/backup/networker/NetworkerClientTest.java
> +    private int getRandomPort() {
Agree. But let's do that in a separate PR.

2023-12-06 12:09 UTC, kishankavala commented
> > Can you create a common util similar to the following to find a free port:
> > ```
> > try (ServerSocket socket = new ServerSocket(0)) {
> >             socket.setReuseAddress(true);
> >             return socket.getLocalPort();
> >         }
> > ```
> 
> +1
> 
> btw, can we specify a port range ?

There are options to specify a range, but didn't look efficient to me.
org.springframework.util.SocketUtils#findAvailableTcpPort(int, int)
Its deprecated as well.

2023-12-06 13:06 UTC, weizhouapache commented on plugins/backup/networker/src/test/java/org/apache/backup/networker/NetworkerClientTest.java
> +                                "                    \"href\": \"http://localhost:9400/nwrestapi/v3/global/protectionpolicies/CSBRONZE\",\n" +
need to use `url` instead,  the port might be different as 9400

```
private final String url =  "http://localhost:" + port + "/nwrestapi/v3";
```

2023-12-06 14:16 UTC, DaanHoogland commented on plugins/backup/networker/src/test/java/org/apache/backup/networker/NetworkerClientTest.java
> +    private int getRandomPort() {
I think we should not do this. let's keep it deterministic.

2023-12-06 14:17 UTC, DaanHoogland requested changes

2023-12-06 14:17 UTC, DaanHoogland commented on plugins/backup/networker/src/test/java/org/apache/backup/networker/NetworkerClientTest.java
> +    private int getRandomPort() {
I think we should not do this. let's keep it deterministic.

2023-12-07 12:21 UTC, shwstppr commented
@vishesh92 cc @DaanHoogland @kishankavala @weizhouapache I propose we move forward with this for now to address build failure and maybe create an issue or PR with more holistic changes to make a common util class to fetch an available port for different tests (in some range). Does that work?

2023-12-07 13:02 UTC, weizhouapache commented
> @vishesh92 cc @DaanHoogland @kishankavala @weizhouapache I propose we move forward with this for now to address build failure and maybe create an issue or PR with more holistic changes to make a common util class to fetch an available port for different tests (in some range). Does that work?

fine with me . let's use port 9400 for now.
if the port is used in a day in the future, we can use another port, it is not an issue.

2023-12-07 13:02 UTC, weizhouapache approved these changes

2023-12-07 13:03 UTC, merged