Add access modifiers to `VirtualMachineTO`
apache/cloudstack pull request #9277
Opened 2024-06-20 13:51 UTC by FelipeM525

### Description

The class `VirtualMachineTO` lacks access modifiers in its fields. This PR aims to improve adherence to object-oriented programming by adding private access modifiers to all fields in the class mentioned above, along with their respective getters and setters.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [x] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI

#### Feature/Enhancement Scale

- [ ] Major
- [x] Minor

### How Has This Been Tested?
I ran all the tests related to `VirtualMachineTO`, checked all usages of the class, and made sure nothing was broken.

2024-06-20 21:26 UTC, winterhazel requested changes

2024-06-20 21:26 UTC, winterhazel commented on api/src/main/java/com/cloud/agent/api/to/VirtualMachineTO.java
>  import com.cloud.vm.VirtualMachine.Type;
```suggestion
import com.cloud.vm.VirtualMachine.Type;

```
Adding the removed line back

2024-08-01 17:27 UTC, JoaoJandre commented
@FelipeM525 there are some test failures

2025-06-05 09:54 UTC, sureshanaparti commented
@blueorangutan package

2025-06-05 09:56 UTC, blueorangutan commented
@sureshanaparti a [SL] Jenkins job has been kicked to build packages. It will be bundled with  KVM, XenServer and VMware SystemVM templates. I'll keep you posted as I make progress.

2025-06-05 12:58 UTC, blueorangutan commented
Packaging result [SF]: ✖️ el8 ✖️ el9 ✖️ debian ✖️ suse15. SL-JID 13629

2025-06-11 19:52 UTC, blueorangutan commented
Packaging result [SF]: ✖️ el8 ✖️ el9 ✖️ debian ✖️ suse15. SL-JID 13722

2025-06-12 09:13 UTC, blueorangutan commented
Packaging result [SF]: ✖️ el8 ✖️ el9 ✖️ debian ✖️ suse15. SL-JID 13739

2025-06-13 14:24 UTC, DaanHoogland commented
@winterhazel , can you assess the status of this PR , please?

2025-06-16 00:52 UTC, winterhazel commented
@blueorangutan package

2025-06-16 00:54 UTC, blueorangutan commented
@winterhazel a [SL] Jenkins job has been kicked to build packages. It will be bundled with  KVM, XenServer and VMware SystemVM templates. I'll keep you posted as I make progress.

2025-06-16 00:54 UTC, winterhazel commented
> @winterhazel , can you assess the status of this PR , please?

@DaanHoogland I fixed the merge conflicts, it should be good to go if the CI passses. I don't think we need more testing for a simple change like this one.

2025-06-16 00:55 UTC, winterhazel approved these changes

2025-06-16 02:02 UTC, blueorangutan commented
Packaging result [SF]: ✔️ el8 ✔️ el9 ✔️ debian ✔️ suse15. SL-JID 13783

2025-06-16 07:24 UTC, DaanHoogland commented
@blueorangutan test

2025-06-16 07:26 UTC, blueorangutan commented
@DaanHoogland a [SL] Trillian-Jenkins test job (ol8 mgmt + kvm-ol8) has been kicked to run smoke tests

2025-06-17 00:29 UTC, blueorangutan commented
<b>[SF] Trillian test result (tid-13532)</b>
Environment: kvm-ol8 (x2), Advanced Networking with Mgmt server ol8
Total time taken: 57953 seconds
Marvin logs: https://github.com/blueorangutan/acs-prs/releases/download/trillian/pr9277-t13532-kvm-ol8.zip
Smoke tests completed. 141 look OK, 0 have errors, 0 did not run
Only failed and skipped tests results shown below:


Test | Result | Time (s) | Test File
--- | --- | --- | ---

2025-06-17 06:34 UTC, DaanHoogland approved these changes
clgtm

2025-06-17 06:35 UTC, merged