custom AccessLogger
apache/cloudstack pull request #9733
Opened 2024-09-26 12:58 UTC by DaanHoogland

### Description

This PR...

Fixes: #9512
as it was only partially fixed in #9568. This PR addresses the access.log candor.

### Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)
- [ ] build/CI
- [ ] test (unit or integration test code)

### Feature/Enhancement Scale or Bug Severity

#### Feature/Enhancement Scale

- [ ] Major
- [ ] Minor

#### Bug Severity

- [ ] BLOCKER
- [ ] Critical
- [ ] Major
- [ ] Minor
- [ ] Trivial

### Screenshots (if appropriate):

### How Has This Been Tested?

#### How did you try to break this feature and the system with this change?

2024-09-26 18:29 UTC, FelipeM525 approved these changes
CLGTM!

2024-09-27 08:42 UTC, DaanHoogland commented
@blueorangutan package

2024-09-27 08:44 UTC, blueorangutan commented
@DaanHoogland a [SL] Jenkins job has been kicked to build packages. It will be bundled with  KVM, XenServer and VMware SystemVM templates. I'll keep you posted as I make progress.

2024-09-27 09:56 UTC, blueorangutan commented
Packaging result [SF]: ✔️ el8 ✔️ el9 ✔️ debian ✔️ suse15. SL-JID 11215

2024-09-27 11:54 UTC, DaanHoogland commented
@blueorangutan test

2024-09-27 11:56 UTC, blueorangutan commented
@DaanHoogland a [SL] Trillian-Jenkins test job (ol8 mgmt + kvm-ol8) has been kicked to run smoke tests

2024-09-28 05:32 UTC, blueorangutan commented
<b>[SF] Trillian test result (tid-11564)</b>
Environment: kvm-ol8 (x2), Advanced Networking with Mgmt server ol8
Total time taken: 61051 seconds
Marvin logs: https://github.com/blueorangutan/acs-prs/releases/download/trillian/pr9733-t11564-kvm-ol8.zip
Smoke tests completed. 139 look OK, 2 have errors, 0 did not run
Only failed and skipped tests results shown below:


Test | Result | Time (s) | Test File
--- | --- | --- | ---
ContextSuite context=TestISOUsage>:setup | `Error` | 0.00 | test_usage.py
test_02_unsecure_vm_migration | `Error` | 496.94 | test_vm_life_cycle.py
test_03_secured_to_nonsecured_vm_migration | `Error` | 281.21 | test_vm_life_cycle.py
test_04_nonsecured_to_secured_vm_migration | `Error` | 379.83 | test_vm_life_cycle.py

2025-01-21 10:16 UTC, blueorangutan commented
@DaanHoogland a [SL] Jenkins job has been kicked to build packages. It will be bundled with  KVM, XenServer and VMware SystemVM templates. I'll keep you posted as I make progress.

2025-01-21 11:28 UTC, blueorangutan commented
Packaging result [SF]: ✔️ el8 ✔️ el9 ✔️ debian ✔️ suse15. SL-JID 12143

2025-01-21 12:21 UTC, DaanHoogland commented
@blueorangutan test

2025-01-21 12:24 UTC, blueorangutan commented
@DaanHoogland a [SL] Trillian-Jenkins test job (ol8 mgmt + kvm-ol8) has been kicked to run smoke tests

2025-01-22 03:38 UTC, blueorangutan commented
<b>[SF] Trillian test result (tid-12145)</b>
Environment: kvm-ol8 (x2), Advanced Networking with Mgmt server ol8
Total time taken: 52343 seconds
Marvin logs: https://github.com/blueorangutan/acs-prs/releases/download/trillian/pr9733-t12145-kvm-ol8.zip
Smoke tests completed. 140 look OK, 1 have errors, 0 did not run
Only failed and skipped tests results shown below:


Test | Result | Time (s) | Test File
--- | --- | --- | ---
test_11_isolated_network_with_dynamic_routed_mode | `Error` | 2.30 | test_ipv4_routing.py
test_12_vpc_and_tier_with_dynamic_routed_mode | `Error` | 2.38 | test_ipv4_routing.py
test_12_vpc_and_tier_with_dynamic_routed_mode | `Error` | 2.38 | test_ipv4_routing.py

2025-02-11 12:58 UTC, DaanHoogland commented
@sureshanaparti could you review/test?

2025-02-11 14:10 UTC, blueorangutan commented
Packaging result [SF]: ✔️ el8 ✔️ el9 ✔️ debian ✔️ suse15. SL-JID 12408

2025-02-11 14:16 UTC, DaanHoogland commented
@blueorangutan test

2025-02-11 14:18 UTC, blueorangutan commented
@DaanHoogland a [SL] Trillian-Jenkins test job (ol8 mgmt + kvm-ol8) has been kicked to run smoke tests

2025-02-12 05:56 UTC, blueorangutan commented
<b>[SF] Trillian test result (tid-12375)</b>
Environment: kvm-ol8 (x2), Advanced Networking with Mgmt server ol8
Total time taken: 53233 seconds
Marvin logs: https://github.com/blueorangutan/acs-prs/releases/download/trillian/pr9733-t12375-kvm-ol8.zip
Smoke tests completed. 132 look OK, 2 have errors, 7 did not run
Only failed and skipped tests results shown below:


Test | Result | Time (s) | Test File
--- | --- | --- | ---
test_11_isolated_network_with_dynamic_routed_mode | `Error` | 2.26 | test_ipv4_routing.py
test_12_vpc_and_tier_with_dynamic_routed_mode | `Error` | 2.39 | test_ipv4_routing.py
test_12_vpc_and_tier_with_dynamic_routed_mode | `Error` | 2.39 | test_ipv4_routing.py
test_12_start_vm_multiple_volumes_allocated | `Error` | 14.89 | test_vm_life_cycle.py
all_test_vpc_redundant | `Skipped` | --- | test_vpc_redundant.py
all_test_vpc_router_nics | `Skipped` | --- | test_vpc_router_nics.py
all_test_vpc_vpn | `Skipped` | --- | test_vpc_vpn.py
all_test_webhook_delivery | `Skipped` | --- | test_webhook_delivery.py
all_test_webhook_lifecycle | `Skipped` | --- | test_webhook_lifecycle.py
all_test_host_maintenance | `Skipped` | --- | test_host_maintenance.py
all_test_hostha_kvm | `Skipped` | --- | test_hostha_kvm.py

2025-02-14 00:57 UTC, blueorangutan commented
<b>[SF] Trillian test result (tid-12389)</b>
Environment: kvm-ol8 (x2), Advanced Networking with Mgmt server ol8
Total time taken: 55402 seconds
Marvin logs: https://github.com/blueorangutan/acs-prs/releases/download/trillian/pr9733-t12389-kvm-ol8.zip
Smoke tests completed. 139 look OK, 2 have errors, 0 did not run
Only failed and skipped tests results shown below:


Test | Result | Time (s) | Test File
--- | --- | --- | ---
test_11_isolated_network_with_dynamic_routed_mode | `Error` | 2.35 | test_ipv4_routing.py
test_12_vpc_and_tier_with_dynamic_routed_mode | `Error` | 2.48 | test_ipv4_routing.py
test_12_vpc_and_tier_with_dynamic_routed_mode | `Error` | 2.48 | test_ipv4_routing.py
test_12_start_vm_multiple_volumes_allocated | `Error` | 17.13 | test_vm_life_cycle.py

2025-08-01 09:03 UTC, rosi-shapeblue requested changes
The session key sanitization is partially working. Testing showed:

**Issue**: The regex `replaceFirst("")` removes `sessionkey=` entirely, creating malformed URLs:
- Expected: `?command=listAccounts&sessionkey=&response=json`
- Actual: `?command=listAccounts&response=json&SessionKeyValue`

**Problems**:
1. Session key values are still exposed in logs (just moved position)
2. URLs are malformed

<img width="3086" height="1854" alt="image" src="https://github.com/user-attachments/assets/50cfc721-433f-46bc-ba66-57b6a45d4f3c" />

2025-08-01 12:26 UTC, DaanHoogland commented
@blueorangutan package

2025-08-01 12:28 UTC, blueorangutan commented
@DaanHoogland a [SL] Jenkins job has been kicked to build packages. It will be bundled with  KVM, XenServer and VMware SystemVM templates. I'll keep you posted as I make progress.

2025-08-01 14:12 UTC, blueorangutan commented
Packaging result [SF]: ✔️ el8 ✔️ el9 ✔️ debian ✔️ suse15. SL-JID 14505

2025-08-04 06:36 UTC, rosi-shapeblue approved these changes
LGTM. Session keys are being completely sanitized from access logs

<img width="3119" height="768" alt="image" src="https://github.com/user-attachments/assets/3b2f2cd6-2b48-4a92-a5da-ffda6801a455" />

2025-08-04 11:06 UTC, merged